import Library.Quadruplet;
import Management.Input;

public class Inputs {
    public static final int phase = 2;

    // Sample data
    // A: Sample input
    // B: Phase 1 expected output
    // C: Phase 2 expected output
    // D: To print or not to print
    public static final Quadruplet<String, Object, Object, Boolean>[] samples = new Quadruplet[]{
            new Quadruplet<>(
                    "kh-tc\n" +
                            "qp-kh\n" +
                            "de-cg\n" +
                            "ka-co\n" +
                            "yn-aq\n" +
                            "qp-ub\n" +
                            "cg-tb\n" +
                            "vc-aq\n" +
                            "tb-ka\n" +
                            "wh-tc\n" +
                            "yn-cg\n" +
                            "kh-ub\n" +
                            "ta-co\n" +
                            "de-co\n" +
                            "tc-td\n" +
                            "tb-wq\n" +
                            "wh-td\n" +
                            "ta-ka\n" +
                            "td-qp\n" +
                            "aq-cg\n" +
                            "wq-ub\n" +
                            "ub-vc\n" +
                            "de-ta\n" +
                            "wq-aq\n" +
                            "wq-vc\n" +
                            "wh-yn\n" +
                            "ka-de\n" +
                            "kh-ta\n" +
                            "co-tc\n" +
                            "wh-qp\n" +
                            "tb-vc\n" +
                            "td-yn"
                    , (Object) 7L
                    , (Object) "co,de,ka,ta"
                    , (Boolean) true
            ),
            new Quadruplet<>(
                    ""
                    , (Object) null
                    , (Object) null
                    , (Boolean) false
            ),
            new Quadruplet<>(
                    ""
                    , (Object) null
                    , (Object) null
                    , (Boolean) false
            ),
    };
    // Puzzle data
    public static final long[] tooLow1  = new long[] {};
    public static final long[] tooHigh1 = new long[] {};
    public static final long[] tooLow2  = new long[] {};
    public static final long[] tooHigh2 = new long[] {};
    public static final boolean printTrueData = false;
    public static final String trueData = "on-za\n" +
            "bp-hs\n" +
            "vc-bg\n" +
            "tm-us\n" +
            "zf-ox\n" +
            "ib-lc\n" +
            "uo-zs\n" +
            "ov-qj\n" +
            "ll-eb\n" +
            "iy-tq\n" +
            "bg-by\n" +
            "un-ix\n" +
            "gi-do\n" +
            "rv-ou\n" +
            "yp-qu\n" +
            "qb-um\n" +
            "qs-dn\n" +
            "ru-ro\n" +
            "et-fw\n" +
            "yx-jt\n" +
            "ns-iz\n" +
            "od-rc\n" +
            "ny-ap\n" +
            "vb-fd\n" +
            "wf-wr\n" +
            "yh-qy\n" +
            "fa-ct\n" +
            "qo-fv\n" +
            "ig-jv\n" +
            "qi-ff\n" +
            "nj-ii\n" +
            "sa-gg\n" +
            "cp-un\n" +
            "ez-kh\n" +
            "vs-du\n" +
            "gp-qs\n" +
            "pt-qj\n" +
            "yp-my\n" +
            "jf-sz\n" +
            "yo-gm\n" +
            "fn-xw\n" +
            "iu-xr\n" +
            "se-ox\n" +
            "mw-ie\n" +
            "fw-br\n" +
            "xy-iu\n" +
            "qw-wi\n" +
            "xc-dq\n" +
            "vb-cq\n" +
            "tw-zj\n" +
            "ka-aq\n" +
            "go-ds\n" +
            "vi-cn\n" +
            "pz-kz\n" +
            "py-nd\n" +
            "pt-ws\n" +
            "og-lw\n" +
            "lb-hj\n" +
            "ef-ac\n" +
            "cv-qa\n" +
            "sq-jv\n" +
            "fw-xk\n" +
            "lu-fc\n" +
            "bj-bp\n" +
            "zh-fi\n" +
            "tg-nm\n" +
            "sp-at\n" +
            "ke-dh\n" +
            "ut-ly\n" +
            "gr-vr\n" +
            "ko-qg\n" +
            "xg-df\n" +
            "rc-up\n" +
            "bd-it\n" +
            "gz-en\n" +
            "qj-ev\n" +
            "wf-dx\n" +
            "xn-hi\n" +
            "pq-th\n" +
            "kr-gw\n" +
            "gu-sm\n" +
            "cv-xr\n" +
            "zq-fp\n" +
            "ep-kq\n" +
            "fv-dx\n" +
            "lc-rw\n" +
            "ey-ef\n" +
            "ek-rw\n" +
            "tw-eg\n" +
            "fc-zw\n" +
            "xm-ho\n" +
            "gj-oy\n" +
            "hy-og\n" +
            "ec-tw\n" +
            "py-hw\n" +
            "qr-jh\n" +
            "vh-ea\n" +
            "vz-ja\n" +
            "ov-ev\n" +
            "yh-vh\n" +
            "yk-fc\n" +
            "fm-yi\n" +
            "yf-kx\n" +
            "er-bi\n" +
            "bi-qq\n" +
            "gc-fk\n" +
            "ie-gf\n" +
            "jk-fn\n" +
            "xl-il\n" +
            "bs-dl\n" +
            "sh-op\n" +
            "py-vx\n" +
            "cn-jl\n" +
            "tl-ee\n" +
            "xw-wn\n" +
            "zv-br\n" +
            "kr-yn\n" +
            "dj-wd\n" +
            "wj-bz\n" +
            "hf-bg\n" +
            "zh-ql\n" +
            "bs-ls\n" +
            "tq-jk\n" +
            "mz-dz\n" +
            "av-jr\n" +
            "gj-dr\n" +
            "po-iy\n" +
            "of-aq\n" +
            "un-fw\n" +
            "nv-bx\n" +
            "jz-nl\n" +
            "ze-ae\n" +
            "vd-df\n" +
            "ix-et\n" +
            "rn-ik\n" +
            "dz-ou\n" +
            "mz-ej\n" +
            "ec-kx\n" +
            "xr-cf\n" +
            "jt-vr\n" +
            "ix-fw\n" +
            "es-er\n" +
            "bv-no\n" +
            "wj-df\n" +
            "yv-cl\n" +
            "jd-xl\n" +
            "lu-vo\n" +
            "xo-td\n" +
            "vq-ow\n" +
            "lc-vm\n" +
            "ca-lf\n" +
            "oq-on\n" +
            "wj-xg\n" +
            "fn-rp\n" +
            "ka-np\n" +
            "bx-ez\n" +
            "dz-sz\n" +
            "kt-xl\n" +
            "dd-jd\n" +
            "la-qn\n" +
            "qe-pt\n" +
            "gl-ly\n" +
            "qj-cc\n" +
            "at-rf\n" +
            "ke-om\n" +
            "dc-hu\n" +
            "qb-rr\n" +
            "ov-ku\n" +
            "tq-xw\n" +
            "fz-tn\n" +
            "ma-hi\n" +
            "br-yw\n" +
            "no-sp\n" +
            "dj-kn\n" +
            "yn-gw\n" +
            "go-ir\n" +
            "bz-xg\n" +
            "wo-se\n" +
            "rz-wa\n" +
            "qy-sx\n" +
            "qn-ym\n" +
            "po-tq\n" +
            "xr-jh\n" +
            "df-tn\n" +
            "oe-vi\n" +
            "sw-el\n" +
            "vm-vr\n" +
            "tg-nf\n" +
            "cg-zt\n" +
            "wf-fl\n" +
            "cd-nc\n" +
            "sw-qa\n" +
            "fo-jg\n" +
            "hj-av\n" +
            "wd-rn\n" +
            "wc-wq\n" +
            "oq-vw\n" +
            "kx-ux\n" +
            "op-nq\n" +
            "sm-ru\n" +
            "ch-fw\n" +
            "qx-uy\n" +
            "ti-fw\n" +
            "rp-qm\n" +
            "po-tj\n" +
            "se-nw\n" +
            "pj-rs\n" +
            "bo-sn\n" +
            "sy-ur\n" +
            "iy-jb\n" +
            "tm-rz\n" +
            "dg-jt\n" +
            "fa-sq\n" +
            "ok-th\n" +
            "zq-ps\n" +
            "hr-kr\n" +
            "pz-zs\n" +
            "wq-ze\n" +
            "ms-an\n" +
            "np-aq\n" +
            "tl-ka\n" +
            "pw-dh\n" +
            "bm-sz\n" +
            "uu-gm\n" +
            "ft-vb\n" +
            "au-ab\n" +
            "lx-lw\n" +
            "cp-ri\n" +
            "ep-xm\n" +
            "ry-hk\n" +
            "yi-gf\n" +
            "cj-qr\n" +
            "fl-lu\n" +
            "bv-za\n" +
            "yw-xk\n" +
            "ne-ss\n" +
            "ln-wv\n" +
            "wf-vo\n" +
            "lx-jy\n" +
            "oy-xy\n" +
            "kq-fa\n" +
            "eh-lv\n" +
            "uq-mi\n" +
            "is-mx\n" +
            "wn-eo\n" +
            "qr-xy\n" +
            "lr-ms\n" +
            "kt-jd\n" +
            "yk-lu\n" +
            "qe-cc\n" +
            "aj-si\n" +
            "qq-bp\n" +
            "lw-xa\n" +
            "us-pp\n" +
            "en-mq\n" +
            "ct-te\n" +
            "od-db\n" +
            "cp-br\n" +
            "rg-ou\n" +
            "ev-ku\n" +
            "qg-ec\n" +
            "uv-np\n" +
            "jn-sw\n" +
            "xj-ie\n" +
            "qr-xr\n" +
            "tr-zp\n" +
            "ha-gg\n" +
            "rx-pz\n" +
            "sa-fl\n" +
            "gx-vz\n" +
            "mg-oi\n" +
            "yc-zn\n" +
            "xw-jo\n" +
            "ae-ou\n" +
            "hj-gn\n" +
            "ix-ri\n" +
            "sq-ct\n" +
            "wo-xr\n" +
            "bl-wl\n" +
            "tt-ac\n" +
            "bs-ij\n" +
            "mh-re\n" +
            "hg-lv\n" +
            "wu-fh\n" +
            "rt-rq\n" +
            "sn-vq\n" +
            "zy-vh\n" +
            "yh-zy\n" +
            "tu-oz\n" +
            "bk-ai\n" +
            "ds-gq\n" +
            "ss-ob\n" +
            "dv-di\n" +
            "vw-on\n" +
            "xr-zb\n" +
            "fr-jl\n" +
            "ro-om\n" +
            "rk-mg\n" +
            "yc-hi\n" +
            "vv-nf\n" +
            "kz-nt\n" +
            "rt-qw\n" +
            "zj-ux\n" +
            "ox-wv\n" +
            "fz-dc\n" +
            "ya-xo\n" +
            "gq-du\n" +
            "mx-fk\n" +
            "si-mo\n" +
            "mo-ef\n" +
            "db-ex\n" +
            "hw-rc\n" +
            "jy-qd\n" +
            "oz-lb\n" +
            "vi-cm\n" +
            "vx-ec\n" +
            "xr-aa\n" +
            "nx-ni\n" +
            "ny-fv\n" +
            "ta-vc\n" +
            "nq-yi\n" +
            "zt-gp\n" +
            "nd-iu\n" +
            "vv-yd\n" +
            "sh-gf\n" +
            "yf-hm\n" +
            "dq-ee\n" +
            "bg-bt\n" +
            "nc-kz\n" +
            "gq-py\n" +
            "ek-sy\n" +
            "ty-le\n" +
            "jo-eo\n" +
            "dy-ko\n" +
            "xa-qd\n" +
            "rm-ns\n" +
            "gk-xp\n" +
            "gz-jr\n" +
            "cr-ez\n" +
            "wr-fc\n" +
            "he-cg\n" +
            "in-og\n" +
            "dw-sh\n" +
            "uk-bf\n" +
            "br-un\n" +
            "ok-gi\n" +
            "ch-gr\n" +
            "cx-gz\n" +
            "dv-ho\n" +
            "bx-cr\n" +
            "ex-go\n" +
            "ik-nv\n" +
            "kh-wb\n" +
            "ol-vk\n" +
            "hg-bf\n" +
            "od-du\n" +
            "vj-qk\n" +
            "yd-uj\n" +
            "fu-lq\n" +
            "bi-bj\n" +
            "vl-il\n" +
            "cd-ob\n" +
            "ax-us\n" +
            "mw-nq\n" +
            "vr-rw\n" +
            "hx-uf\n" +
            "wz-vb\n" +
            "em-xe\n" +
            "ee-of\n" +
            "hm-ec\n" +
            "ek-ds\n" +
            "ys-sy\n" +
            "qq-jq\n" +
            "gu-jg\n" +
            "zc-oi\n" +
            "ji-yb\n" +
            "ou-kw\n" +
            "ep-lh\n" +
            "id-nx\n" +
            "gp-wp\n" +
            "ph-ns\n" +
            "cn-io\n" +
            "wn-tq\n" +
            "rw-vm\n" +
            "nx-fv\n" +
            "ce-gn\n" +
            "vr-lt\n" +
            "xl-dd\n" +
            "zw-sa\n" +
            "wr-ty\n" +
            "kz-jx\n" +
            "jd-rx\n" +
            "na-hk\n" +
            "nc-ob\n" +
            "nw-re\n" +
            "wt-jq\n" +
            "aj-sw\n" +
            "kc-bi\n" +
            "wq-qx\n" +
            "jt-ib\n" +
            "cb-ly\n" +
            "uj-zp\n" +
            "cy-ps\n" +
            "sm-om\n" +
            "bu-bd\n" +
            "ux-ko\n" +
            "xa-hy\n" +
            "bc-uq\n" +
            "si-sw\n" +
            "yc-ma\n" +
            "yk-sa\n" +
            "gf-mw\n" +
            "bp-eq\n" +
            "fh-zh\n" +
            "mn-bo\n" +
            "bw-hj\n" +
            "es-bj\n" +
            "op-xj\n" +
            "up-hh\n" +
            "ds-db\n" +
            "gx-qu\n" +
            "yo-fp\n" +
            "wg-ls\n" +
            "et-zc\n" +
            "dn-vw\n" +
            "yb-bt\n" +
            "sk-sb\n" +
            "xe-ea\n" +
            "ni-ap\n" +
            "hw-go\n" +
            "dn-zc\n" +
            "no-vw\n" +
            "pt-cc\n" +
            "rv-wc\n" +
            "wc-xq\n" +
            "jg-ke\n" +
            "oo-jg\n" +
            "do-ss\n" +
            "ie-nq\n" +
            "pq-is\n" +
            "rf-oq\n" +
            "zn-vb\n" +
            "eb-ef\n" +
            "gp-rs\n" +
            "pt-pf\n" +
            "md-lb\n" +
            "le-zw\n" +
            "xn-tf\n" +
            "ui-cb\n" +
            "bz-fz\n" +
            "pj-gp\n" +
            "zr-ee\n" +
            "pp-ax\n" +
            "kl-jq\n" +
            "xc-of\n" +
            "ox-lr\n" +
            "uy-rv\n" +
            "vd-sb\n" +
            "yy-bh\n" +
            "vn-dq\n" +
            "dt-hg\n" +
            "np-vn\n" +
            "la-fh\n" +
            "gw-eh\n" +
            "cq-wz\n" +
            "no-ia\n" +
            "qj-ws\n" +
            "pl-pt\n" +
            "df-ge\n" +
            "zq-vj\n" +
            "jg-om\n" +
            "nq-sh\n" +
            "zy-kr\n" +
            "pv-im\n" +
            "aq-vn\n" +
            "sq-yx\n" +
            "sb-df\n" +
            "ih-gx\n" +
            "gn-av\n" +
            "dc-ff\n" +
            "wg-ph\n" +
            "sm-fo\n" +
            "ux-dk\n" +
            "gi-kv\n" +
            "hr-dt\n" +
            "rc-go\n" +
            "ax-tm\n" +
            "pp-bo\n" +
            "nn-xe\n" +
            "jf-mz\n" +
            "vl-jd\n" +
            "fs-cl\n" +
            "gz-gn\n" +
            "ui-ly\n" +
            "rx-hy\n" +
            "rn-dj\n" +
            "qe-pf\n" +
            "jx-gy\n" +
            "tr-qb\n" +
            "eu-lr\n" +
            "yt-ih\n" +
            "tr-oi\n" +
            "nc-ss\n" +
            "nh-pb\n" +
            "ir-nd\n" +
            "el-qf\n" +
            "tl-aq\n" +
            "kj-es\n" +
            "ru-fo\n" +
            "fw-bu\n" +
            "ps-qk\n" +
            "lq-lx\n" +
            "cm-fg\n" +
            "el-si\n" +
            "vs-hw\n" +
            "eg-ux\n" +
            "mt-lh\n" +
            "tt-yy\n" +
            "jz-sq\n" +
            "fm-nq\n" +
            "vx-ko\n" +
            "bl-lx\n" +
            "rc-ex\n" +
            "by-ji\n" +
            "eq-kl\n" +
            "tk-vd\n" +
            "mo-qf\n" +
            "zr-xd\n" +
            "bt-vc\n" +
            "ux-mi\n" +
            "ha-us\n" +
            "vr-ib\n" +
            "hx-rq\n" +
            "at-no\n" +
            "ui-tx\n" +
            "vs-od\n" +
            "fp-ay\n" +
            "zj-kx\n" +
            "vs-ds\n" +
            "qo-vk\n" +
            "hw-db\n" +
            "pf-ku\n" +
            "md-jr\n" +
            "fp-fe\n" +
            "yg-tx\n" +
            "mz-gs\n" +
            "nl-ct\n" +
            "cn-oe\n" +
            "xj-ri\n" +
            "ya-ku\n" +
            "nw-mh\n" +
            "vh-ff\n" +
            "ft-hz\n" +
            "en-md\n" +
            "ps-fp\n" +
            "af-rx\n" +
            "vx-kx\n" +
            "kv-fd\n" +
            "kr-lf\n" +
            "ae-rg\n" +
            "sp-vw\n" +
            "vn-zr\n" +
            "ea-pi\n" +
            "at-vw\n" +
            "rw-ax\n" +
            "kg-vh\n" +
            "xy-cv\n" +
            "ca-gw\n" +
            "em-nn\n" +
            "hj-en\n" +
            "gw-ra\n" +
            "fr-cy\n" +
            "ed-wu\n" +
            "yf-tw\n" +
            "uo-lz\n" +
            "gc-pq\n" +
            "tw-ux\n" +
            "qy-kg\n" +
            "cx-fo\n" +
            "it-ly\n" +
            "uj-mg\n" +
            "rp-po\n" +
            "sq-yv\n" +
            "zh-zs\n" +
            "th-ne\n" +
            "es-fe\n" +
            "rn-nv\n" +
            "aa-gj\n" +
            "zb-aa\n" +
            "wt-kl\n" +
            "wu-uo\n" +
            "bb-ce\n" +
            "by-bt\n" +
            "qb-gv\n" +
            "bp-es\n" +
            "bd-tx\n" +
            "ma-cq\n" +
            "yt-qu\n" +
            "uu-mn\n" +
            "ke-fa\n" +
            "mx-jn\n" +
            "dq-ew\n" +
            "ax-ow\n" +
            "hv-dx\n" +
            "yh-sx\n" +
            "gx-ry\n" +
            "jz-jv\n" +
            "sb-wj\n" +
            "do-ok\n" +
            "gj-qn\n" +
            "br-ri\n" +
            "lu-zw\n" +
            "sb-ge\n" +
            "kg-ao\n" +
            "uu-fp\n" +
            "us-xh\n" +
            "dd-jb\n" +
            "xp-wi\n" +
            "cf-cj\n" +
            "hm-zj\n" +
            "le-sa\n" +
            "wf-ty\n" +
            "qx-xq\n" +
            "oi-rr\n" +
            "bl-og\n" +
            "mq-hj\n" +
            "dw-xi\n" +
            "aw-ap\n" +
            "sk-cs\n" +
            "wu-yq\n" +
            "gm-zq\n" +
            "na-ry\n" +
            "wp-pj\n" +
            "ne-gy\n" +
            "dt-yn\n" +
            "au-bm\n" +
            "rk-ur\n" +
            "nm-oi\n" +
            "af-zm\n" +
            "cd-ss\n" +
            "dj-ez\n" +
            "cf-oy\n" +
            "ce-md\n" +
            "th-kz\n" +
            "nt-cd\n" +
            "rm-iz\n" +
            "jz-fs\n" +
            "ni-qo\n" +
            "jx-do\n" +
            "zy-xe\n" +
            "ls-uq\n" +
            "sy-jt\n" +
            "wa-xh\n" +
            "lf-lv\n" +
            "ys-jt\n" +
            "ij-wg\n" +
            "jw-mw\n" +
            "bk-ef\n" +
            "yx-ek\n" +
            "vr-cm\n" +
            "jv-sk\n" +
            "dw-ej\n" +
            "mo-pq\n" +
            "ov-pl\n" +
            "fz-ge\n" +
            "mt-ep\n" +
            "cq-hz\n" +
            "za-zc\n" +
            "lj-uy\n" +
            "rv-ae\n" +
            "se-ln\n" +
            "kw-ze\n" +
            "wo-ln\n" +
            "vo-zw\n" +
            "wd-fd\n" +
            "xo-pl\n" +
            "mx-gc\n" +
            "ln-lr\n" +
            "sy-rw\n" +
            "gy-fs\n" +
            "zy-ea\n" +
            "kc-er\n" +
            "fl-le\n" +
            "te-we\n" +
            "hy-bl\n" +
            "vp-hi\n" +
            "xx-jd\n" +
            "lv-yn\n" +
            "wn-fn\n" +
            "oq-no\n" +
            "dl-wg\n" +
            "um-qx\n" +
            "jf-dz\n" +
            "ac-ll\n" +
            "hv-nh\n" +
            "td-cc\n" +
            "mz-im\n" +
            "wf-pr\n" +
            "bt-xy\n" +
            "rr-uj\n" +
            "cm-mt\n" +
            "ed-qn\n" +
            "qy-ea\n" +
            "gg-xh\n" +
            "mn-mj\n" +
            "hf-nj\n" +
            "qk-yo\n" +
            "hu-oo\n" +
            "mh-zf\n" +
            "an-nw\n" +
            "fi-ql\n" +
            "dj-sn\n" +
            "mz-ab\n" +
            "dy-yf\n" +
            "id-nh\n" +
            "zj-eg\n" +
            "gu-as\n" +
            "ya-td\n" +
            "xw-jk\n" +
            "hh-ll\n" +
            "xd-of\n" +
            "tj-eo\n" +
            "bv-on\n" +
            "yd-tg\n" +
            "dd-xx\n" +
            "vn-ee\n" +
            "nf-uj\n" +
            "gk-de\n" +
            "la-fi\n" +
            "ow-us\n" +
            "dk-ec\n" +
            "gm-jl\n" +
            "ho-io\n" +
            "zn-hz\n" +
            "rt-wi\n" +
            "ai-up\n" +
            "gs-fs\n" +
            "ma-ig\n" +
            "pq-fk\n" +
            "ev-pf\n" +
            "fh-lz\n" +
            "md-gz\n" +
            "ku-ft\n" +
            "uf-uk\n" +
            "vk-hv\n" +
            "mx-si\n" +
            "ys-yx\n" +
            "si-qf\n" +
            "vp-ty\n" +
            "qi-bz\n" +
            "ep-ho\n" +
            "pg-vm\n" +
            "sk-fs\n" +
            "yy-hh\n" +
            "lx-in\n" +
            "qj-ku\n" +
            "ey-eb\n" +
            "en-av\n" +
            "kh-we\n" +
            "rf-ia\n" +
            "ty-sa\n" +
            "jy-ub\n" +
            "nl-fs\n" +
            "pl-yi\n" +
            "cn-mt\n" +
            "pi-ao\n" +
            "nq-xj\n" +
            "rm-uq\n" +
            "at-oq\n" +
            "ni-dx\n" +
            "sm-dh\n" +
            "mx-qa\n" +
            "jq-bi\n" +
            "ze-kc\n" +
            "fa-cl\n" +
            "yq-qn\n" +
            "kx-hm\n" +
            "ym-ql\n" +
            "ie-jw\n" +
            "jx-nt\n" +
            "cv-zb\n" +
            "zt-wb\n" +
            "yf-dk\n" +
            "uj-tg\n" +
            "dk-vx\n" +
            "ju-ij\n" +
            "in-wl\n" +
            "xr-cj\n" +
            "nd-go\n" +
            "fa-fs\n" +
            "ay-yo\n" +
            "om-fo\n" +
            "ta-ji\n" +
            "vr-lc\n" +
            "zm-dd\n" +
            "qk-uu\n" +
            "zv-wb\n" +
            "xm-cn\n" +
            "xm-cm\n" +
            "ja-tn\n" +
            "rk-cb\n" +
            "jd-af\n" +
            "vm-sy\n" +
            "mo-gc\n" +
            "mj-my\n" +
            "zs-yq\n" +
            "kl-er\n" +
            "gx-yp\n" +
            "fs-sq\n" +
            "fi-ym\n" +
            "ja-ry\n" +
            "bz-sb\n" +
            "rv-ia\n" +
            "dn-ia\n" +
            "gx-mj\n" +
            "ly-hs\n" +
            "eq-wt\n" +
            "ec-zj\n" +
            "sp-oq\n" +
            "la-ym\n" +
            "lc-sy\n" +
            "hw-gq\n" +
            "id-aw\n" +
            "id-ny\n" +
            "od-zm\n" +
            "ez-rn\n" +
            "si-jn\n" +
            "lb-ce\n" +
            "ws-ya\n" +
            "ry-ih\n" +
            "yg-bg\n" +
            "ls-rm\n" +
            "si-pq\n" +
            "tn-ff\n" +
            "hz-vb\n" +
            "ej-im\n" +
            "rx-kt\n" +
            "sy-yx\n" +
            "yy-ac\n" +
            "ir-od\n" +
            "du-rc\n" +
            "ux-qg\n" +
            "mj-yp\n" +
            "wp-wb\n" +
            "fz-pb\n" +
            "eb-yy\n" +
            "ay-cy\n" +
            "tr-rr\n" +
            "uq-iz\n" +
            "jg-cx\n" +
            "ze-ou\n" +
            "kx-dk\n" +
            "np-xc\n" +
            "rk-yg\n" +
            "sb-tn\n" +
            "oe-fo\n" +
            "sh-sp\n" +
            "gg-ow\n" +
            "mi-ls\n" +
            "im-dz\n" +
            "bj-er\n" +
            "nj-yb\n" +
            "rb-bt\n" +
            "ut-rk\n" +
            "au-jf\n" +
            "yd-tr\n" +
            "kq-yv\n" +
            "rg-ze\n" +
            "qd-wl\n" +
            "zt-uv\n" +
            "ok-jx\n" +
            "jt-xo\n" +
            "lq-fk\n" +
            "ea-uf\n" +
            "qm-oz\n" +
            "de-so\n" +
            "ui-ut\n" +
            "xn-vb\n" +
            "ok-kz\n" +
            "vn-tl\n" +
            "qo-nh\n" +
            "jk-jo\n" +
            "xd-xc\n" +
            "sk-sq\n" +
            "hv-pb\n" +
            "jg-cy\n" +
            "ob-do\n" +
            "oo-cx\n" +
            "op-ko\n" +
            "bv-vt\n" +
            "kj-er\n" +
            "op-tk\n" +
            "pj-cg\n" +
            "cd-gy\n" +
            "re-eu\n" +
            "qr-cf\n" +
            "oa-mz\n" +
            "ws-cc\n" +
            "sn-wa\n" +
            "ep-bs\n" +
            "xy-xr\n" +
            "pi-xe\n" +
            "kw-ae\n" +
            "vs-nd\n" +
            "dc-tn\n" +
            "rv-ze\n" +
            "rq-uf\n" +
            "du-go\n" +
            "gg-wa\n" +
            "ac-up\n" +
            "bh-ac\n" +
            "sp-za\n" +
            "oo-zx\n" +
            "sn-gg\n" +
            "rf-sp\n" +
            "nq-tk\n" +
            "nc-vs\n" +
            "gf-dw\n" +
            "eo-iy\n" +
            "ge-vd\n" +
            "ge-wj\n" +
            "vx-ux\n" +
            "nf-nm\n" +
            "sd-sx\n" +
            "vr-yx\n" +
            "uy-jl\n" +
            "om-ru\n" +
            "xk-br\n" +
            "zr-aq\n" +
            "re-zf\n" +
            "bg-ii\n" +
            "ro-ke\n" +
            "gu-fo\n" +
            "xk-ix\n" +
            "fh-ql\n" +
            "ie-rg\n" +
            "td-ov\n" +
            "xj-mw\n" +
            "hr-ws\n" +
            "ez-nv\n" +
            "wz-po\n" +
            "ek-vm\n" +
            "xj-xi\n" +
            "rs-we\n" +
            "el-mo\n" +
            "wa-us\n" +
            "jy-xa\n" +
            "eq-jq\n" +
            "re-ln\n" +
            "po-jo\n" +
            "by-hh\n" +
            "xr-dr\n" +
            "mg-tr\n" +
            "em-vh\n" +
            "pf-ya\n" +
            "bd-ui\n" +
            "lz-wu\n" +
            "tz-io\n" +
            "qf-pq\n" +
            "ae-wq\n" +
            "ql-lz\n" +
            "ri-ti\n" +
            "mh-an\n" +
            "vd-ff\n" +
            "oq-dn\n" +
            "fk-mj\n" +
            "ut-fq\n" +
            "do-kz\n" +
            "fm-xi\n" +
            "hz-tf\n" +
            "lj-xq\n" +
            "ub-hy\n" +
            "jq-kj\n" +
            "zm-ue\n" +
            "kv-ez\n" +
            "uk-qw\n" +
            "nx-ig\n" +
            "pv-dz\n" +
            "bz-hu\n" +
            "gn-bb\n" +
            "fl-tz\n" +
            "bf-xp\n" +
            "jk-jb\n" +
            "oe-ho\n" +
            "nj-rb\n" +
            "te-he\n" +
            "jg-zx\n" +
            "ii-rb\n" +
            "ql-zs\n" +
            "et-xk\n" +
            "pt-td\n" +
            "bm-rj\n" +
            "so-hx\n" +
            "ce-db\n" +
            "qa-qf\n" +
            "ph-bs\n" +
            "sg-by\n" +
            "cf-iu\n" +
            "zh-ym\n" +
            "ut-cb\n" +
            "zn-xn\n" +
            "ri-et\n" +
            "tj-rp\n" +
            "sh-xi\n" +
            "dr-zb\n" +
            "ea-yh\n" +
            "io-xm\n" +
            "ab-sd\n" +
            "jw-sh\n" +
            "zc-sp\n" +
            "nc-gy\n" +
            "px-rt\n" +
            "dd-vl\n" +
            "mi-ij\n" +
            "dn-rf\n" +
            "xd-ka\n" +
            "tg-qb\n" +
            "af-pz\n" +
            "iu-oy\n" +
            "bh-eb\n" +
            "ui-hs\n" +
            "zx-om\n" +
            "qp-cy\n" +
            "pq-el\n" +
            "ff-ge\n" +
            "ox-an\n" +
            "kr-ol\n" +
            "ux-hm\n" +
            "pf-qj\n" +
            "aq-dq\n" +
            "kd-xl\n" +
            "wg-zh\n" +
            "pw-ra\n" +
            "mi-bc\n" +
            "nm-zp\n" +
            "lw-hy\n" +
            "ui-fq\n" +
            "nn-ea\n" +
            "hs-tx\n" +
            "gm-vj\n" +
            "ik-mb\n" +
            "aa-cj\n" +
            "we-gp\n" +
            "xe-yh\n" +
            "pj-kh\n" +
            "mq-bb\n" +
            "om-cx\n" +
            "nw-wu\n" +
            "gm-cy\n" +
            "rz-bo\n" +
            "cs-cl\n" +
            "jy-in\n" +
            "ay-gm\n" +
            "hr-eh\n" +
            "qw-rq\n" +
            "gu-dh\n" +
            "ne-nt\n" +
            "jf-im\n" +
            "cv-iu\n" +
            "up-ll\n" +
            "mx-aj\n" +
            "et-bu\n" +
            "zm-qi\n" +
            "mn-yt\n" +
            "rp-iy\n" +
            "ql-qn\n" +
            "in-lw\n" +
            "fw-ev\n" +
            "vp-yc\n" +
            "yg-gl\n" +
            "bd-rk\n" +
            "in-xa\n" +
            "lh-io\n" +
            "pg-wb\n" +
            "fg-ho\n" +
            "yi-dw\n" +
            "wn-rp\n" +
            "ge-nm\n" +
            "te-wp\n" +
            "yg-ui\n" +
            "eq-es\n" +
            "gi-th\n" +
            "xx-vl\n" +
            "rq-so\n" +
            "us-cp\n" +
            "ol-yn\n" +
            "oy-zb\n" +
            "ku-cc\n" +
            "qa-fk\n" +
            "de-bf\n" +
            "cx-gu\n" +
            "vz-na\n" +
            "hj-ce\n" +
            "yf-ec\n" +
            "jo-tj\n" +
            "wn-po\n" +
            "mz-pv\n" +
            "mo-mx\n" +
            "bv-oq\n" +
            "ch-ix\n" +
            "tj-qm\n" +
            "vq-wa\n" +
            "kr-pw\n" +
            "tn-bz\n" +
            "wq-ou\n" +
            "lk-tl\n" +
            "zr-np\n" +
            "jz-ct\n" +
            "wa-tm\n" +
            "xx-zm\n" +
            "ft-cq\n" +
            "kl-bi\n" +
            "yt-xk\n" +
            "yi-jw\n" +
            "ol-ca\n" +
            "dw-mw\n" +
            "of-ka\n" +
            "lk-ee\n" +
            "wt-bp\n" +
            "pw-lv\n" +
            "di-io\n" +
            "kl-fe\n" +
            "vx-eg\n" +
            "ws-ev\n" +
            "qp-fr\n" +
            "pp-wa\n" +
            "ex-od\n" +
            "ch-xk\n" +
            "zw-pr\n" +
            "yd-nf\n" +
            "wu-zs\n" +
            "tm-ha\n" +
            "qp-xd\n" +
            "ws-vo\n" +
            "ju-ls\n" +
            "gq-ir\n" +
            "yx-lt\n" +
            "uk-de\n" +
            "lq-ne\n" +
            "hk-ja\n" +
            "hq-nv\n" +
            "nn-zy\n" +
            "nq-dw\n" +
            "im-sz\n" +
            "cd-dl\n" +
            "xm-fg\n" +
            "ni-nh\n" +
            "qe-ws\n" +
            "wv-vc\n" +
            "tj-fn\n" +
            "na-fm\n" +
            "vs-rc\n" +
            "ly-fq\n" +
            "ps-qp\n" +
            "tt-ef\n" +
            "rw-lt\n" +
            "dy-vx\n" +
            "ff-sb\n" +
            "fm-tk\n" +
            "wi-uk\n" +
            "cf-jh\n" +
            "eb-ai\n" +
            "ed-fh\n" +
            "lb-gz\n" +
            "xe-sx\n" +
            "qy-zq\n" +
            "jk-qm\n" +
            "ew-xc\n" +
            "gz-bb\n" +
            "hs-gl\n" +
            "fu-ub\n" +
            "tz-le\n" +
            "pg-yx\n" +
            "pw-ol\n" +
            "xi-vv\n" +
            "yp-mn\n" +
            "xc-aq\n" +
            "rv-kw\n" +
            "wr-sa\n" +
            "bd-hs\n" +
            "qm-jo\n" +
            "ij-bc\n" +
            "lw-ub\n" +
            "sz-oa\n" +
            "nj-bg\n" +
            "wv-eu\n" +
            "yq-uo\n" +
            "ty-zw\n" +
            "is-fk\n" +
            "yy-ef\n" +
            "gy-kz\n" +
            "lt-ib\n" +
            "qo-id\n" +
            "lh-cn\n" +
            "ue-xx\n" +
            "zf-wo\n" +
            "rx-ue\n" +
            "gz-av\n" +
            "wt-es\n" +
            "bo-wa\n" +
            "hq-wd\n" +
            "an-lr\n" +
            "jq-es\n" +
            "by-nj\n" +
            "jb-jo\n" +
            "tt-eb\n" +
            "jw-fm\n" +
            "ab-ti\n" +
            "pr-tz\n" +
            "fg-io\n" +
            "vo-fl\n" +
            "oz-jr\n" +
            "mw-kj\n" +
            "og-ub\n" +
            "ca-pw\n" +
            "wu-la\n" +
            "tl-zr\n" +
            "po-qm\n" +
            "ia-qs\n" +
            "pr-fq\n" +
            "ra-hr\n" +
            "iu-aa\n" +
            "fg-lh\n" +
            "im-oa\n" +
            "kc-qq\n" +
            "ut-gf\n" +
            "lq-jy\n" +
            "xh-ax\n" +
            "jx-cd\n" +
            "ri-gr\n" +
            "ne-ob\n" +
            "sd-bm\n" +
            "ce-en\n" +
            "ij-rm\n" +
            "ra-dt\n" +
            "oi-yd\n" +
            "qg-zj\n" +
            "tl-of\n" +
            "ek-lc\n" +
            "xh-rz\n" +
            "kw-ix\n" +
            "ce-tu\n" +
            "ry-vz\n" +
            "ef-hh\n" +
            "pw-eh\n" +
            "dx-ap\n" +
            "fe-eq\n" +
            "fl-wr\n" +
            "uk-so\n" +
            "fz-xg\n" +
            "eg-kx\n" +
            "wu-ql\n" +
            "ex-vs\n" +
            "qm-tq\n" +
            "zp-yd\n" +
            "kt-il\n" +
            "ty-vo\n" +
            "gi-ss\n" +
            "vv-mg\n" +
            "ih-mj\n" +
            "zv-rs\n" +
            "ym-lz\n" +
            "fq-bd\n" +
            "ej-sd\n" +
            "gp-kh\n" +
            "kq-jv\n" +
            "fh-uo\n" +
            "yk-le\n" +
            "nj-ji\n" +
            "kx-qg\n" +
            "cj-oy\n" +
            "hy-jy\n" +
            "oa-ej\n" +
            "wf-sa\n" +
            "pv-rj\n" +
            "an-zf\n" +
            "bu-ix\n" +
            "zn-cq\n" +
            "yt-vz\n" +
            "vm-yx\n" +
            "rn-vw\n" +
            "nf-mg\n" +
            "zy-pi\n" +
            "bm-jf\n" +
            "xd-dq\n" +
            "ob-eo\n" +
            "tl-ys\n" +
            "ze-wc\n" +
            "bw-sg\n" +
            "qf-is\n" +
            "ey-ai\n" +
            "fu-xa\n" +
            "av-md\n" +
            "cx-as\n" +
            "ik-ez\n" +
            "gn-oz\n" +
            "jv-yv\n" +
            "qk-jl\n" +
            "au-rj\n" +
            "sm-of\n" +
            "xe-kg\n" +
            "gn-jr\n" +
            "vq-xh\n" +
            "go-vs\n" +
            "xp-px\n" +
            "mb-bx\n" +
            "lx-qd\n" +
            "fs-yv\n" +
            "at-dn\n" +
            "nv-mb\n" +
            "lu-wf\n" +
            "fd-kn\n" +
            "sb-hu\n" +
            "fo-dh\n" +
            "ds-ex\n" +
            "is-mo\n" +
            "ze-uy\n" +
            "ke-zx\n" +
            "fm-op\n" +
            "tx-cb\n" +
            "hr-ol\n" +
            "zn-zr\n" +
            "rn-bx\n" +
            "xa-lx\n" +
            "py-du\n" +
            "pb-ny\n" +
            "ct-cs\n" +
            "zm-il\n" +
            "rg-qx\n" +
            "mq-lb\n" +
            "aj-gc\n" +
            "uo-ed\n" +
            "aj-qf\n" +
            "rq-bf\n" +
            "nc-do\n" +
            "lr-dt\n" +
            "ct-yv\n" +
            "wo-eu\n" +
            "bd-ly\n" +
            "gc-sw\n" +
            "cq-xn\n" +
            "xx-pz\n" +
            "qw-xp\n" +
            "xg-qi\n" +
            "cr-ly\n" +
            "ue-vl\n" +
            "zm-rx\n" +
            "wt-fe\n" +
            "dq-ka\n" +
            "ao-dx\n" +
            "sh-tk\n" +
            "pw-yn\n" +
            "ub-uo\n" +
            "ln-mh\n" +
            "qq-fe\n" +
            "di-cm\n" +
            "ft-vp\n" +
            "xx-rx\n" +
            "xj-sh\n" +
            "gg-bo\n" +
            "rw-ys\n" +
            "on-qs\n" +
            "af-xl\n" +
            "yw-gr\n" +
            "ek-jt\n" +
            "gr-ix\n" +
            "fr-vj\n" +
            "eg-ey\n" +
            "tg-vv\n" +
            "jk-eo\n" +
            "cg-wp\n" +
            "zt-we\n" +
            "dq-tl\n" +
            "mj-na\n" +
            "zt-cn\n" +
            "ig-wz\n" +
            "fr-fp\n" +
            "rp-xw\n" +
            "ko-yf\n" +
            "pl-qj\n" +
            "ro-zx\n" +
            "rf-bv\n" +
            "te-pj\n" +
            "bf-hx\n" +
            "yv-nl\n" +
            "ur-tx\n" +
            "bh-up\n" +
            "tr-tg\n" +
            "pb-aw\n" +
            "mn-hk\n" +
            "oq-pg\n" +
            "rg-rv\n" +
            "iy-wn\n" +
            "lb-gn\n" +
            "qe-bx\n" +
            "se-an\n" +
            "bk-tt\n" +
            "as-ru\n" +
            "hu-qi\n" +
            "do-nt\n" +
            "wq-uy\n" +
            "jw-xi\n" +
            "bp-bi\n" +
            "ne-nc\n" +
            "xh-ow\n" +
            "fg-ik\n" +
            "pv-gk\n" +
            "oa-ab\n" +
            "qg-dk\n" +
            "pt-xo\n" +
            "hx-qw\n" +
            "kz-cd\n" +
            "of-lk\n" +
            "oa-dz\n" +
            "ef-up\n" +
            "tx-rf\n" +
            "qi-wj\n" +
            "wo-ox\n" +
            "cr-hq\n" +
            "sx-ea\n" +
            "zj-ji\n" +
            "ju-bs\n" +
            "ro-as\n" +
            "mj-ry\n" +
            "ll-bk\n" +
            "rq-xp\n" +
            "bf-qw\n" +
            "vi-di\n" +
            "mt-hz\n" +
            "on-rf\n" +
            "rm-mi\n" +
            "fg-mt\n" +
            "xm-id\n" +
            "fp-qk\n" +
            "na-ja\n" +
            "na-mn\n" +
            "ay-jl\n" +
            "fv-id\n" +
            "aw-ny\n" +
            "uu-zq\n" +
            "zc-on\n" +
            "vz-qu\n" +
            "vo-yk\n" +
            "wi-hx\n" +
            "sd-rj\n" +
            "lb-bb\n" +
            "tm-bo\n" +
            "tu-hj\n" +
            "vw-rf\n" +
            "pv-au\n" +
            "df-ff\n" +
            "gq-vs\n" +
            "ra-eh\n" +
            "kl-kc\n" +
            "dk-zj\n" +
            "ep-io\n" +
            "aj-hf\n" +
            "hj-oz\n" +
            "tk-jw\n" +
            "lv-ra\n" +
            "xc-dv\n" +
            "th-cd\n" +
            "ph-yy\n" +
            "pg-jt\n" +
            "zs-fi\n" +
            "jd-zb\n" +
            "ta-hf\n" +
            "pt-ku\n" +
            "gs-jz\n" +
            "ll-bh\n" +
            "sw-pq\n" +
            "vm-le\n" +
            "eg-ko\n" +
            "eh-hg\n" +
            "dv-lh\n" +
            "wj-vd\n" +
            "nc-th\n" +
            "qa-si\n" +
            "yg-ur\n" +
            "no-on\n" +
            "fv-vk\n" +
            "gq-rc\n" +
            "ct-fs\n" +
            "hk-my\n" +
            "iz-ii\n" +
            "dr-cf\n" +
            "kd-xx\n" +
            "nn-pi\n" +
            "ma-zn\n" +
            "it-rk\n" +
            "it-hs\n" +
            "yf-ob\n" +
            "jg-ro\n" +
            "ct-sk\n" +
            "yc-pi\n" +
            "du-ex\n" +
            "ti-et\n" +
            "no-zc\n" +
            "lf-dt\n" +
            "gw-hg\n" +
            "gs-cs\n" +
            "sp-dn\n" +
            "ju-rm\n" +
            "hg-lf\n" +
            "ge-dc\n" +
            "wt-qq\n" +
            "mi-bs\n" +
            "ib-ek\n" +
            "ke-fo\n" +
            "bf-uf\n" +
            "lh-vi\n" +
            "cc-xo\n" +
            "el-fk\n" +
            "zt-kh\n" +
            "rs-he\n" +
            "qf-ls\n" +
            "qg-tw\n" +
            "rg-kw\n" +
            "cm-dv\n" +
            "jf-pv\n" +
            "jh-cv\n" +
            "jo-tq\n" +
            "vj-yo\n" +
            "my-wt\n" +
            "xc-lk\n" +
            "wz-ft\n" +
            "uv-he\n" +
            "vd-bz\n" +
            "bk-jk\n" +
            "zs-lz\n" +
            "td-ku\n" +
            "go-db\n" +
            "yn-eh\n" +
            "jd-il\n" +
            "ok-yb\n" +
            "re-nt\n" +
            "eu-zf\n" +
            "jq-ij\n" +
            "gm-bz\n" +
            "fd-dj\n" +
            "yw-un\n" +
            "px-uf\n" +
            "gl-lf\n" +
            "md-oz\n" +
            "mh-se\n" +
            "dg-yx\n" +
            "ll-ey\n" +
            "jf-rj\n" +
            "jr-lb\n" +
            "un-gr\n" +
            "xg-sb\n" +
            "yg-it\n" +
            "nn-qy\n" +
            "yo-jl\n" +
            "zj-yf\n" +
            "nd-od\n" +
            "fe-bp\n" +
            "qq-on\n" +
            "bd-ur\n" +
            "on-dn\n" +
            "cl-sq\n" +
            "wt-kc\n" +
            "cg-te\n" +
            "qr-do\n" +
            "ji-sg\n" +
            "cl-sk\n" +
            "eg-dy\n" +
            "ke-ru\n" +
            "dq-zr\n" +
            "mg-yd\n" +
            "ff-wj\n" +
            "ju-mi\n" +
            "sg-yq\n" +
            "ln-eu\n" +
            "hz-ma\n" +
            "kt-pz\n" +
            "ub-bl\n" +
            "lb-av\n" +
            "rs-wp\n" +
            "fn-jo\n" +
            "er-qq\n" +
            "jt-lt\n" +
            "la-ed\n" +
            "yh-em\n" +
            "bm-dz\n" +
            "au-sd\n" +
            "ie-sh\n" +
            "ed-ym\n" +
            "sa-ka\n" +
            "lv-kr\n" +
            "ed-yq\n" +
            "bo-vq\n" +
            "kn-wd\n" +
            "od-hw\n" +
            "io-dv\n" +
            "zn-wz\n" +
            "nl-jv\n" +
            "el-jn\n" +
            "aa-qr\n" +
            "hf-vc\n" +
            "qp-fp\n" +
            "um-ae\n" +
            "aq-px\n" +
            "ep-di\n" +
            "cp-xk\n" +
            "as-ke\n" +
            "ao-xe\n" +
            "oy-cv\n" +
            "bm-im\n" +
            "ur-ut\n" +
            "bk-ey\n" +
            "ff-au\n" +
            "pg-lt\n" +
            "mj-yt\n" +
            "vq-tm\n" +
            "gy-ok\n" +
            "ex-ir\n" +
            "wu-qn\n" +
            "tg-zp\n" +
            "pl-pf\n" +
            "yy-ai\n" +
            "yy-up\n" +
            "jy-fu\n" +
            "sb-dc\n" +
            "oo-om\n" +
            "kd-dd\n" +
            "ry-my\n" +
            "yc-tf\n" +
            "qf-bm\n" +
            "gl-tx\n" +
            "gc-qf\n" +
            "ni-ny\n" +
            "bb-hj\n" +
            "th-ss\n" +
            "ho-cn\n" +
            "ia-oq\n" +
            "xc-tl\n" +
            "ix-br\n" +
            "ri-bu\n" +
            "lr-re\n" +
            "qg-yh\n" +
            "lt-ys\n" +
            "zp-qu\n" +
            "wj-hu\n" +
            "nw-lr\n" +
            "bl-tw\n" +
            "we-cg\n" +
            "de-uy\n" +
            "xn-lt\n" +
            "pv-sd\n" +
            "kq-cl\n" +
            "iy-jo\n" +
            "xk-bu\n" +
            "ds-hw\n" +
            "iu-zb\n" +
            "tw-kx\n" +
            "dg-ek\n" +
            "ch-ti\n" +
            "ms-mh\n" +
            "xn-ig\n" +
            "ps-vj\n" +
            "tx-fq\n" +
            "tt-ai\n" +
            "ep-cm\n" +
            "ap-id\n" +
            "te-wb\n" +
            "hk-yp\n" +
            "yp-na\n" +
            "kw-um\n" +
            "gx-na\n" +
            "zy-kg\n" +
            "xp-de\n" +
            "za-no\n" +
            "tq-tj\n" +
            "pw-gw\n" +
            "df-dc\n" +
            "an-wv\n" +
            "fv-ni\n" +
            "ss-jx\n" +
            "ra-kr\n" +
            "ph-ju\n" +
            "rq-wi\n" +
            "qq-bj\n" +
            "fp-vj\n" +
            "bs-ns\n" +
            "vt-ai\n" +
            "vm-lt\n" +
            "xw-qm\n" +
            "ys-vm\n" +
            "is-si\n" +
            "uf-wi\n" +
            "rb-ta\n" +
            "ll-tt\n" +
            "fz-hu\n" +
            "pw-lf\n" +
            "jh-cj\n" +
            "vt-bh\n" +
            "ec-ux\n" +
            "mb-wd\n" +
            "an-ln\n" +
            "kd-kt\n" +
            "vp-vb\n" +
            "ta-ii\n" +
            "yt-hk\n" +
            "ez-wd\n" +
            "po-jk\n" +
            "vr-ys\n" +
            "bi-eq\n" +
            "cj-gj\n" +
            "yb-bw\n" +
            "ik-kn\n" +
            "qu-my\n" +
            "xc-zr\n" +
            "ro-oo\n" +
            "fc-le\n" +
            "ob-gi\n" +
            "fd-hq\n" +
            "mt-oe\n" +
            "wg-rm\n" +
            "qe-ku\n" +
            "hq-mb\n" +
            "rg-wc\n" +
            "py-vs\n" +
            "rw-yx\n" +
            "fk-jn\n" +
            "bl-fu\n" +
            "ed-zs\n" +
            "dq-np\n" +
            "ji-hf\n" +
            "ia-vw\n" +
            "dc-qi\n" +
            "ms-wv\n" +
            "dd-rx\n" +
            "es-yw\n" +
            "xj-tk\n" +
            "ka-lk\n" +
            "ll-vj\n" +
            "nl-cs\n" +
            "ur-hs\n" +
            "qx-ze\n" +
            "gi-nt\n" +
            "hz-yc\n" +
            "va-ea\n" +
            "xk-ti\n" +
            "ov-ya\n" +
            "lf-fc\n" +
            "cf-cv\n" +
            "gy-nt\n" +
            "zc-at\n" +
            "fi-qn\n" +
            "sa-tz\n" +
            "fa-yv\n" +
            "tx-rk\n" +
            "wu-zh\n" +
            "jw-op\n" +
            "ui-rk\n" +
            "ox-eu\n" +
            "wl-lw\n" +
            "cp-et\n" +
            "eq-er\n" +
            "yb-ii\n" +
            "fv-nh\n" +
            "qj-ya\n" +
            "bs-iz\n" +
            "qb-nf\n" +
            "fn-iy\n" +
            "aa-xy\n" +
            "ty-fc\n" +
            "um-uy\n" +
            "dv-vi\n" +
            "hh-ai\n" +
            "pi-va\n" +
            "ol-lf\n" +
            "bj-jq\n" +
            "db-nd\n" +
            "bk-jx\n" +
            "cs-sq\n" +
            "cp-ch\n" +
            "fh-av\n" +
            "te-rs\n" +
            "kj-bj\n" +
            "nn-va\n" +
            "hz-hi\n" +
            "zs-la\n" +
            "wz-hz\n" +
            "ge-tn\n" +
            "nt-nc\n" +
            "sz-ej\n" +
            "zv-zt\n" +
            "ow-sn\n" +
            "cv-qr\n" +
            "rm-mq\n" +
            "xp-so\n" +
            "th-gy\n" +
            "gv-nf\n" +
            "vp-wz\n" +
            "ii-sg\n" +
            "dy-kx\n" +
            "ee-yv\n" +
            "xd-rk\n" +
            "nc-jx\n" +
            "jh-tq\n" +
            "fd-nv\n" +
            "yh-va\n" +
            "er-wt\n" +
            "fd-mb\n" +
            "lj-rv\n" +
            "qg-yf\n" +
            "rm-dl\n" +
            "gk-hx\n" +
            "ue-dd\n" +
            "sm-ro\n" +
            "rs-kh\n" +
            "uj-jf\n" +
            "vl-pz\n" +
            "qg-eg\n" +
            "xc-vn\n" +
            "bt-bw\n" +
            "ss-kz\n" +
            "cn-cm\n" +
            "vo-tz\n" +
            "lf-eh\n" +
            "ju-wg\n" +
            "fm-yo\n" +
            "nt-th\n" +
            "ws-pl\n" +
            "yw-fw\n" +
            "ek-lt\n" +
            "bj-fe\n" +
            "eq-pf\n" +
            "wv-wo\n" +
            "xe-vh\n" +
            "kl-bj\n" +
            "ut-hs\n" +
            "zm-xl\n" +
            "jw-dw\n" +
            "ne-do\n" +
            "ku-pl\n" +
            "ty-fl\n" +
            "ny-qo\n" +
            "jh-xy\n" +
            "ms-ox\n" +
            "mg-rr\n" +
            "ok-ss\n" +
            "qe-ev\n" +
            "kv-cr\n" +
            "ha-rz\n" +
            "mx-yq\n" +
            "oi-vv\n" +
            "se-wv\n" +
            "dt-ca\n" +
            "en-gn\n" +
            "sd-oa\n" +
            "io-oe\n" +
            "fk-sw\n" +
            "gs-jv\n" +
            "ji-bw\n" +
            "dr-iu\n" +
            "lw-bl\n" +
            "du-nd\n" +
            "vl-kt\n" +
            "lf-yn\n" +
            "yk-uv\n" +
            "pt-gx\n" +
            "px-bf\n" +
            "wn-jb\n" +
            "uk-xp\n" +
            "nx-dx\n" +
            "gk-qw\n" +
            "vj-ay\n" +
            "uk-hx\n" +
            "wa-ax\n" +
            "bf-so\n" +
            "ow-wa\n" +
            "yt-ja\n" +
            "cx-ru\n" +
            "im-au\n" +
            "ax-rz\n" +
            "td-cg\n" +
            "vq-nf\n" +
            "sx-em\n" +
            "he-kh\n" +
            "og-xa\n" +
            "ac-ey\n" +
            "mn-my\n" +
            "th-do\n" +
            "qk-zq\n" +
            "jq-bp\n" +
            "uj-gv\n" +
            "qm-eo\n" +
            "ni-vk\n" +
            "ya-pt\n" +
            "aa-oy\n" +
            "jh-gj\n" +
            "hm-qg\n" +
            "vk-pb\n" +
            "ry-mn\n" +
            "cd-ne\n" +
            "dk-tw\n" +
            "dr-jh\n" +
            "he-zv\n" +
            "dl-iz\n" +
            "ds-du\n" +
            "us-gg\n" +
            "yh-ao\n" +
            "oz-ce\n" +
            "ws-ku\n" +
            "ee-ka\n" +
            "on-at\n" +
            "px-wi\n" +
            "fm-xj\n" +
            "jz-fp\n" +
            "ib-rw\n" +
            "qb-nm\n" +
            "cs-yv\n" +
            "oe-di\n" +
            "jb-fn\n" +
            "ac-eb\n" +
            "xi-ie\n" +
            "ab-jf\n" +
            "xj-yi\n" +
            "ge-xg\n" +
            "np-ew\n" +
            "lk-xd\n" +
            "ox-nw\n" +
            "sh-mw\n" +
            "xn-vp\n" +
            "is-qa\n" +
            "gk-bf\n" +
            "ju-uq\n" +
            "ew-ed\n" +
            "lh-xm\n" +
            "zt-rs\n" +
            "tj-wn\n" +
            "xy-cj\n" +
            "sg-rb\n" +
            "ax-sn\n" +
            "xg-dc\n" +
            "yb-sg\n" +
            "fi-fv\n" +
            "gn-mq\n" +
            "ab-rj\n" +
            "fa-sk\n" +
            "ov-pt\n" +
            "en-qg\n" +
            "fl-pr\n" +
            "dx-qo\n" +
            "ay-ps\n" +
            "mq-oz\n" +
            "sq-kq\n" +
            "ys-ib\n" +
            "ry-yt\n" +
            "ow-cc\n" +
            "uf-rt\n" +
            "ov-ws\n" +
            "zp-oi\n" +
            "nn-di\n" +
            "hr-yn\n" +
            "eb-up\n" +
            "rg-wq\n" +
            "oo-gu\n" +
            "gs-kq\n" +
            "eq-dg\n" +
            "vx-tw\n" +
            "lb-en\n" +
            "gj-xy\n" +
            "gw-dt\n" +
            "sz-mz\n" +
            "is-jn\n" +
            "uo-qn\n" +
            "et-un\n" +
            "tx-it\n" +
            "qi-vd\n" +
            "lx-og\n" +
            "em-qy\n" +
            "pl-ev\n" +
            "pg-lc\n" +
            "ay-fr\n" +
            "hg-ra\n" +
            "ee-np\n" +
            "hg-ol\n" +
            "nj-bw\n" +
            "wo-re\n" +
            "jg-ru\n" +
            "nn-oo\n" +
            "ty-pr\n" +
            "wc-kw\n" +
            "vt-ac\n" +
            "ie-tk\n" +
            "yk-zw\n" +
            "ha-bo\n" +
            "tf-ma\n" +
            "oe-lh\n" +
            "nf-zp\n" +
            "ze-um\n" +
            "mi-ns\n" +
            "hx-xp\n" +
            "bu-ch\n" +
            "sm-jg\n" +
            "jk-tj\n" +
            "tm-cq\n" +
            "wd-bj\n" +
            "sp-on\n" +
            "ih-xe\n" +
            "jr-ce\n" +
            "gj-iu\n" +
            "nm-gv\n" +
            "oo-ru\n" +
            "up-vt\n" +
            "em-lu\n" +
            "jl-vj\n" +
            "hr-lv\n" +
            "ia-at\n" +
            "uv-we\n" +
            "bt-ji\n" +
            "zw-wr\n" +
            "ue-il\n" +
            "du-nj\n" +
            "ne-ok\n" +
            "hm-eg\n" +
            "lc-ys\n" +
            "ep-oe\n" +
            "ej-ab\n" +
            "mn-ja\n" +
            "zc-rf\n" +
            "gv-zp\n" +
            "dh-ru\n" +
            "bc-py\n" +
            "cv-aa\n" +
            "as-wi\n" +
            "dr-oy\n" +
            "rb-bw\n" +
            "ro-dh\n" +
            "cr-wd\n" +
            "jr-en\n" +
            "vm-ib\n" +
            "xd-tl\n" +
            "vl-xl\n" +
            "ps-im\n" +
            "fk-mo\n" +
            "fa-cs\n" +
            "pj-nh\n" +
            "lv-dt\n" +
            "gz-ce\n" +
            "yn-nl\n" +
            "sz-gu\n" +
            "rq-px\n" +
            "vo-fc\n" +
            "gz-tu\n" +
            "ur-gl\n" +
            "lk-ew\n" +
            "la-ql\n" +
            "fv-pb\n" +
            "nm-mg\n" +
            "cd-do\n" +
            "nx-vk\n" +
            "fc-wf\n" +
            "ss-gy\n" +
            "wl-lq\n" +
            "jb-qm\n" +
            "pq-jn\n" +
            "fq-it\n" +
            "cl-vo\n" +
            "gf-jw\n" +
            "bb-jr\n" +
            "gm-ps\n" +
            "ut-gl\n" +
            "up-bk\n" +
            "rz-bi\n" +
            "kj-qq\n" +
            "oe-fg\n" +
            "sq-gs\n" +
            "qs-no\n" +
            "qe-pl\n" +
            "cc-pf\n" +
            "aw-fv\n" +
            "by-ii\n" +
            "pr-fc\n" +
            "mn-ih\n" +
            "mb-wr\n" +
            "lw-lq\n" +
            "bc-ls\n" +
            "qi-fz\n" +
            "jy-ya\n" +
            "zf-nw\n" +
            "ys-dg\n" +
            "cp-ti\n" +
            "wl-xa\n" +
            "cb-yg\n" +
            "iy-tj\n" +
            "un-ch\n" +
            "wv-re\n" +
            "yp-vz\n" +
            "aq-ew\n" +
            "op-ie\n" +
            "em-ao\n" +
            "mh-ai\n" +
            "ym-zs\n" +
            "ie-dw\n" +
            "xm-oe\n" +
            "kh-te\n" +
            "mb-rn\n" +
            "sn-ha\n" +
            "xj-jw\n" +
            "ed-fi\n" +
            "kr-dt\n" +
            "vp-we\n" +
            "hr-hg\n" +
            "kn-cr\n" +
            "wc-ae\n" +
            "rm-ph\n" +
            "bv-ia\n" +
            "kv-dj\n" +
            "ny-hv\n" +
            "em-ea\n" +
            "ob-nt\n" +
            "wl-fu\n" +
            "zv-te\n" +
            "ia-on\n" +
            "rs-cg\n" +
            "tm-gg\n" +
            "ih-qu\n" +
            "xw-iy\n" +
            "ut-it\n" +
            "qp-yo\n" +
            "ch-et\n" +
            "fi-yq\n" +
            "tt-bb\n" +
            "yw-ri\n" +
            "ew-va\n" +
            "qw-so\n" +
            "el-gc\n" +
            "ui-qj\n" +
            "wb-we\n" +
            "ji-rb\n" +
            "gi-jx\n" +
            "ju-kt\n" +
            "dg-rw\n" +
            "kw-uy\n" +
            "ct-gs\n" +
            "dc-lh\n" +
            "dr-cv\n" +
            "tq-ln\n" +
            "mx-pq\n" +
            "uf-xp\n" +
            "ep-dv\n" +
            "gm-qk\n" +
            "jg-as\n" +
            "vd-dc\n" +
            "gl-it\n" +
            "qu-mj\n" +
            "vx-zj\n" +
            "hx-px\n" +
            "so-px\n" +
            "il-kd\n" +
            "bw-by\n" +
            "up-tt\n" +
            "ih-na\n" +
            "aw-hv\n" +
            "ib-dg\n" +
            "it-cb\n" +
            "mj-vz\n" +
            "fk-aj\n" +
            "ue-xl\n" +
            "qp-ay\n" +
            "fl-za\n" +
            "kn-hq\n" +
            "sy-dg\n" +
            "sm-cx\n" +
            "se-gc\n" +
            "uq-wg\n" +
            "ce-mq\n" +
            "bs-wg\n" +
            "kg-sx\n" +
            "qn-fh\n" +
            "ge-hu\n" +
            "ma-vp\n" +
            "rg-xq\n" +
            "pr-vo\n" +
            "rr-zp\n" +
            "ib-fd\n" +
            "jk-rp\n" +
            "sn-pp\n" +
            "vn-ew\n" +
            "kt-ue\n" +
            "nx-qo\n" +
            "jn-dk\n" +
            "nw-eu\n" +
            "jf-sd\n" +
            "aj-is\n" +
            "ll-yy\n" +
            "vr-sy\n" +
            "gp-zv\n" +
            "sd-mz\n" +
            "pi-qy\n" +
            "og-wl\n" +
            "id-dx\n" +
            "qp-gm\n" +
            "ew-zr\n" +
            "bg-sg\n" +
            "bg-yb\n" +
            "xi-mw\n" +
            "tr-uj\n" +
            "yk-pr\n" +
            "rt-xp\n" +
            "te-gp\n" +
            "fu-lx\n" +
            "gr-xk\n" +
            "se-eu\n" +
            "mn-qu\n" +
            "id-vk\n" +
            "oq-ry\n" +
            "yk-wf\n" +
            "pf-ov\n" +
            "hi-wz\n" +
            "tk-yi\n" +
            "sw-mx\n" +
            "jq-kc\n" +
            "zq-fr\n" +
            "ef-ll\n" +
            "nl-gs\n" +
            "tj-jb\n" +
            "fn-po\n" +
            "fr-gm\n" +
            "yk-wr\n" +
            "qd-lq\n" +
            "fv-hv\n" +
            "pg-sy\n" +
            "ti-br\n" +
            "zj-ko\n" +
            "fz-sb\n" +
            "hu-tn\n" +
            "gr-bu\n" +
            "zt-te\n" +
            "zc-vw\n" +
            "wi-xa\n" +
            "tu-jr\n" +
            "dt-pw\n" +
            "xw-ym\n" +
            "oi-uj\n" +
            "dy-ux\n" +
            "un-ri\n" +
            "at-qs\n" +
            "pz-dd\n" +
            "sk-yv\n" +
            "fm-sh\n" +
            "px-gk\n" +
            "dn-za\n" +
            "vq-ax\n" +
            "fu-hy\n" +
            "il-af\n" +
            "he-pj\n" +
            "af-kt\n" +
            "eq-bj\n" +
            "in-bl\n" +
            "uo-ym\n" +
            "cl-jz\n" +
            "ta-bl\n" +
            "ne-kz\n" +
            "dr-aa\n" +
            "in-tj\n" +
            "zf-ln\n" +
            "bv-vw\n" +
            "ex-nd\n" +
            "fu-qd\n" +
            "vt-yy\n" +
            "ef-ai\n" +
            "yk-fl\n" +
            "hz-ig\n" +
            "jn-qf\n" +
            "gk-rt\n" +
            "ob-kz\n" +
            "qd-bl\n" +
            "fg-dv\n" +
            "ox-ln\n" +
            "ps-fr\n" +
            "xa-ub\n" +
            "pp-rz\n" +
            "bd-yg\n" +
            "qf-mx\n" +
            "nd-hw\n" +
            "jn-gc\n" +
            "rr-kl\n" +
            "ay-qk\n" +
            "cl-nl\n" +
            "vv-zp\n" +
            "bw-vc\n" +
            "tf-wz\n" +
            "jl-qp\n" +
            "wj-tn\n" +
            "nj-sg\n" +
            "eu-an\n" +
            "jn-mo\n" +
            "rc-py\n" +
            "ta-bt\n" +
            "uv-cg\n" +
            "nv-dj\n" +
            "fd-ik\n" +
            "fp-gm\n" +
            "yt-gx\n" +
            "ok-cd\n" +
            "zf-ms\n" +
            "vs-db\n" +
            "tw-hm\n" +
            "tz-fc\n" +
            "wc-ou\n" +
            "aj-mo\n" +
            "nh-lk\n" +
            "bc-bs\n" +
            "cr-fd\n" +
            "ch-ri\n" +
            "pw-hg\n" +
            "ni-aw\n" +
            "dc-wj\n" +
            "at-za\n" +
            "ri-fw\n" +
            "kg-va\n" +
            "vh-sx\n" +
            "fh-ss\n" +
            "pi-yh\n" +
            "nx-ap\n" +
            "hf-bt\n" +
            "nv-ch\n" +
            "kw-wq\n" +
            "jb-xw\n" +
            "hf-bw\n" +
            "ii-hf\n" +
            "fv-ap\n" +
            "dz-rj\n" +
            "rf-za\n" +
            "za-ia\n" +
            "pp-vq\n" +
            "kq-sk\n" +
            "xd-ee\n" +
            "cb-hs\n" +
            "re-ox\n" +
            "zy-qy\n" +
            "vc-yb\n" +
            "jy-wl\n" +
            "pf-xo\n" +
            "zy-ao\n" +
            "ur-cb\n" +
            "xc-ee\n" +
            "xh-pp\n" +
            "aw-vk\n" +
            "qw-px\n" +
            "gc-si\n" +
            "lu-pr\n" +
            "uv-wp\n" +
            "tz-wf\n" +
            "lj-wq\n" +
            "qi-tn\n" +
            "yp-rq\n" +
            "xy-zb\n" +
            "va-sx\n" +
            "ao-ea\n" +
            "qs-sp\n" +
            "hf-rb\n" +
            "ob-jx\n" +
            "ig-vb\n" +
            "bu-cp\n" +
            "ds-rc\n" +
            "vq-ha\n" +
            "gl-cb\n" +
            "tm-xh\n" +
            "pp-rp\n" +
            "nn-ao\n" +
            "ti-ix\n" +
            "cm-io\n" +
            "he-bo\n" +
            "jq-er\n" +
            "tu-mq\n" +
            "is-gc\n" +
            "ej-rj\n" +
            "he-zt\n" +
            "ee-ew\n" +
            "gi-kz\n" +
            "um-ou\n" +
            "tz-yk\n" +
            "xy-dr\n" +
            "wp-ca\n" +
            "sx-sk\n" +
            "ev-cc\n" +
            "ri-xk\n" +
            "mh-wv\n" +
            "bv-qs\n" +
            "kj-eq\n" +
            "cg-kh\n" +
            "tf-sm\n" +
            "fo-as\n" +
            "ep-fg\n" +
            "jq-fe\n" +
            "vo-wr\n" +
            "di-lh\n" +
            "mq-gz\n" +
            "kg-xq\n" +
            "dv-oe\n" +
            "rv-xq\n" +
            "lx-wl\n" +
            "qm-iy\n" +
            "yd-gv\n" +
            "fg-di\n" +
            "ql-uo\n" +
            "hh-bk\n" +
            "wv-lr\n" +
            "rz-gg\n" +
            "qy-vh\n" +
            "de-yd\n" +
            "lv-hi\n" +
            "er-wj\n" +
            "gq-qd\n" +
            "xg-vd\n" +
            "lw-jy\n" +
            "og-lq\n" +
            "xq-ze\n" +
            "qa-el\n" +
            "rr-gv\n" +
            "un-ti\n" +
            "vb-hi\n" +
            "dt-ol\n" +
            "rf-no\n" +
            "xm-vi\n" +
            "uk-rt\n" +
            "bh-hh\n" +
            "rk-ly\n" +
            "gw-hr\n" +
            "rn-kn\n" +
            "rs-it\n" +
            "dz-ab\n" +
            "th-jx\n" +
            "nw-wo\n" +
            "bo-us\n" +
            "yg-fq\n" +
            "kr-eh\n" +
            "md-tu\n" +
            "ta-by\n" +
            "uk-gk\n" +
            "qo-xq\n" +
            "ch-br\n" +
            "ke-gu\n" +
            "ig-hi\n" +
            "tf-ft\n" +
            "cc-ov\n" +
            "cr-ik\n" +
            "fh-ym\n" +
            "ih-ja\n" +
            "pv-ab\n" +
            "dh-oo\n" +
            "de-qw\n" +
            "hy-wl\n" +
            "rs-uv\n" +
            "of-vn\n" +
            "so-fr\n" +
            "us-rz\n" +
            "nd-rc\n" +
            "tz-wr\n" +
            "bt-nj\n" +
            "se-re\n" +
            "aj-qa\n" +
            "uy-wc\n" +
            "yg-ut\n" +
            "ij-uq\n" +
            "vi-mt\n" +
            "wv-nw\n" +
            "bi-wt\n" +
            "hm-dk\n" +
            "jz-yv\n" +
            "ie-fm\n" +
            "ui-ur\n" +
            "nm-yd\n" +
            "lz-ed\n" +
            "pv-sz\n" +
            "dy-ec\n" +
            "fi-wu\n" +
            "el-go\n" +
            "qr-zb\n" +
            "bv-zc\n" +
            "yq-ym\n" +
            "hy-lq\n" +
            "yf-ux\n" +
            "tf-vp\n" +
            "rs-wb\n" +
            "my-na\n" +
            "pj-we\n" +
            "lj-ze\n" +
            "kc-bp\n" +
            "mj-hk\n" +
            "mt-dv\n" +
            "cm-lh\n" +
            "ls-ph\n" +
            "qo-hv\n" +
            "au-ej\n" +
            "ew-tl\n" +
            "qa-gc\n" +
            "aq-lk\n" +
            "dl-bc\n" +
            "ns-bc\n" +
            "ho-vi\n" +
            "mz-rj\n" +
            "rx-il\n" +
            "bf-wi\n" +
            "wn-qm\n" +
            "oa-pv\n" +
            "by-yb\n" +
            "gv-tg\n" +
            "rt-bf\n" +
            "ir-py\n" +
            "vt-hh\n" +
            "pj-zv\n" +
            "nd-gq\n" +
            "ay-tg\n" +
            "du-db\n" +
            "kx-aa\n" +
            "gf-nq\n" +
            "mt-io\n" +
            "xa-lq\n" +
            "av-bb\n" +
            "df-yw\n" +
            "pi-sx\n" +
            "qj-qe\n" +
            "in-ub\n" +
            "es-kl\n" +
            "uv-kh\n" +
            "nx-hv\n" +
            "fm-gf\n" +
            "ns-wg\n" +
            "rn-kv\n" +
            "fi-uo\n" +
            "wb-cg\n" +
            "cs-jz\n" +
            "xo-ev\n" +
            "vc-ii\n" +
            "jy-bl\n" +
            "qj-td\n" +
            "wq-xq\n" +
            "ae-qx\n" +
            "gn-tu\n" +
            "tu-av\n" +
            "cr-rn\n" +
            "yw-cp\n" +
            "ra-ol\n" +
            "zn-ft\n" +
            "de-rt\n" +
            "cc-pl\n" +
            "ik-hq\n" +
            "gv-kn\n" +
            "sx-ao\n" +
            "zq-jl\n" +
            "vn-ez\n" +
            "le-lu\n" +
            "tk-gf\n" +
            "ds-py\n" +
            "eb-cj\n" +
            "mg-gv\n" +
            "vj-uu\n" +
            "my-ja\n" +
            "nf-tr\n" +
            "lr-wo\n" +
            "gi-ne\n" +
            "cp-ix\n" +
            "gy-gi\n" +
            "xq-um\n" +
            "mi-wg\n" +
            "dh-jg\n" +
            "pz-jd\n" +
            "bz-dc\n" +
            "jl-cy\n" +
            "hu-xg\n" +
            "rw-pg\n" +
            "eu-ms\n" +
            "yp-ja\n" +
            "he-wp\n" +
            "pr-le\n" +
            "oi-qb\n" +
            "dy-zj\n" +
            "zw-wf\n" +
            "an-wo\n" +
            "vh-va\n" +
            "df-bz\n" +
            "yv-gs\n" +
            "yi-sh\n" +
            "lj-um\n" +
            "ue-af\n" +
            "pz-ue\n" +
            "ik-wd\n" +
            "uy-ae\n" +
            "ro-fo\n" +
            "rr-yd\n" +
            "fq-hs\n" +
            "le-wr\n" +
            "lz-yq\n" +
            "vt-ef\n" +
            "kv-kn\n" +
            "ll-vt\n" +
            "ti-yw\n" +
            "jh-oy\n" +
            "ir-hw\n" +
            "ni-qk\n" +
            "hq-rn\n" +
            "kt-zm\n" +
            "tf-cq\n" +
            "jn-qa\n" +
            "bl-xa\n" +
            "qx-lj\n" +
            "nc-gi\n" +
            "kj-kc\n" +
            "ji-vl\n" +
            "bx-ik\n" +
            "se-lr\n" +
            "zr-of\n" +
            "zx-ru\n" +
            "hx-vi\n" +
            "np-xd\n" +
            "io-vi\n" +
            "ha-xh\n" +
            "kr-hg\n" +
            "dw-xj\n" +
            "tg-mg\n" +
            "hq-bx\n" +
            "cr-nv\n" +
            "ik-dj\n" +
            "pp-tm\n" +
            "wr-pr\n" +
            "ft-ig\n" +
            "lt-lc\n" +
            "fr-uu\n" +
            "ek-pg\n" +
            "em-va\n" +
            "dr-qr\n" +
            "ca-yn\n" +
            "bh-ef\n" +
            "ql-ed\n" +
            "bt-sg\n" +
            "ly-tx\n" +
            "oo-fo\n" +
            "ra-lf\n" +
            "kn-bx\n" +
            "kw-lj\n" +
            "rw-jt\n" +
            "ne-jx\n" +
            "kq-jz\n" +
            "jf-ej\n" +
            "ig-yc\n" +
            "ap-vk\n" +
            "sn-us\n" +
            "se-ms\n" +
            "ea-kg\n" +
            "hq-dj\n" +
            "qx-kw\n" +
            "we-zv\n" +
            "ry-qu\n" +
            "en-tu\n" +
            "av-mq\n" +
            "uf-qw\n" +
            "ol-eh\n" +
            "hu-vd\n" +
            "db-rc\n" +
            "gp-cg\n" +
            "tz-zw\n" +
            "di-mt\n" +
            "np-tl\n" +
            "dt-eh\n" +
            "nx-ny\n" +
            "fa-jv\n" +
            "gr-br\n" +
            "rv-wq\n" +
            "zh-ed\n" +
            "fz-ff\n" +
            "fh-zs\n" +
            "kd-rx\n" +
            "tt-hh\n" +
            "lj-ou\n" +
            "tn-vd\n" +
            "mi-ph\n" +
            "fa-jz\n" +
            "zx-fo\n" +
            "ur-it\n" +
            "eo-tq\n" +
            "hz-xn\n" +
            "ny-ru\n" +
            "yc-cq\n" +
            "hu-df\n" +
            "yn-hg\n" +
            "ms-ln\n" +
            "ct-kq\n" +
            "oz-en\n" +
            "ka-xc\n" +
            "qd-og\n" +
            "mh-ox\n" +
            "qj-xo\n" +
            "tm-sn\n" +
            "lj-wc\n" +
            "rg-uy\n" +
            "oa-jf\n" +
            "hx-rt\n" +
            "vh-nn\n" +
            "hv-ni\n" +
            "zy-va\n" +
            "la-uo\n" +
            "oz-wq\n" +
            "ho-di\n" +
            "ij-dl\n" +
            "du-hw\n" +
            "ir-rc\n" +
            "uo-zh\n" +
            "xl-rx\n" +
            "sd-im\n" +
            "qf-sw\n" +
            "ra-lc\n" +
            "gw-lv\n" +
            "bi-kj\n" +
            "jd-zm\n" +
            "yf-vx\n" +
            "lq-in\n" +
            "rg-lj\n" +
            "de-rq\n" +
            "cj-cv\n" +
            "cc-ya\n" +
            "pz-il\n" +
            "ja-gx\n" +
            "vl-rx\n" +
            "ie-yi\n" +
            "un-bu\n" +
            "lz-zh\n" +
            "vk-dx\n" +
            "hy-qd\n" +
            "yw-et\n" +
            "ow-dn\n" +
            "ta-sg\n" +
            "kj-wt\n" +
            "fu-lw\n" +
            "db-gq\n" +
            "jr-hj\n" +
            "bb-tu\n" +
            "eu-dy\n" +
            "pt-ev\n" +
            "vq-us\n" +
            "xe-qy\n" +
            "ns-dl\n" +
            "ao-va\n" +
            "nx-pb\n" +
            "ft-hi\n" +
            "lk-dq\n" +
            "zm-kd\n" +
            "gr-et\n" +
            "zm-vl\n" +
            "gk-uf\n" +
            "wp-zt\n" +
            "lx-ub\n" +
            "fd-bx\n" +
            "ae-bz\n" +
            "ay-uu\n" +
            "aq-ee\n" +
            "ib-yx\n" +
            "ha-ax\n" +
            "bk-yy\n" +
            "qq-kl\n" +
            "yp-yt\n" +
            "bj-wt\n" +
            "tw-ko\n" +
            "zx-sm\n" +
            "zs-qn\n" +
            "pi-vh\n" +
            "ey-yy\n" +
            "oy-xr\n" +
            "cj-iu\n" +
            "zq-ay\n" +
            "jo-wn\n" +
            "po-jb\n" +
            "sz-au\n" +
            "pi-kg\n" +
            "xd-aq\n" +
            "gi-cd\n" +
            "gw-hq\n" +
            "jr-mq\n" +
            "qq-es\n" +
            "dk-dy\n" +
            "ab-im\n" +
            "gx-hk\n" +
            "aj-el\n" +
            "gk-rq\n" +
            "sg-vc\n" +
            "qp-zq\n" +
            "yd-qb\n" +
            "ya-qe\n" +
            "ta-bw\n" +
            "dz-au\n" +
            "tw-dy\n" +
            "vb-yc\n" +
            "ax-gg\n" +
            "av-cf\n" +
            "xo-ov\n" +
            "ez-hq\n" +
            "dx-pb\n" +
            "ja-mj\n" +
            "pq-qa\n" +
            "au-oa\n" +
            "ju-bc\n" +
            "gg-vq\n" +
            "rk-fq\n" +
            "dg-lc\n" +
            "hk-qu\n" +
            "gk-wi\n" +
            "ru-gu\n" +
            "le-wf\n" +
            "rj-sz\n" +
            "kd-gn\n" +
            "iy-dy\n" +
            "hm-ko\n" +
            "ey-up\n" +
            "vv-gv\n" +
            "lb-ms\n" +
            "pp-ha\n" +
            "bs-uq\n" +
            "ka-vn\n" +
            "td-ws\n" +
            "nd-ds\n" +
            "ai-ll\n" +
            "yi-op\n" +
            "tg-rr\n" +
            "oo-as\n" +
            "ib-sy\n" +
            "sp-bv\n" +
            "td-ev\n" +
            "vr-dg\n" +
            "dg-pg\n" +
            "wn-jk\n" +
            "dh-om\n" +
            "ko-kx\n" +
            "xi-nq\n" +
            "uq-dl\n" +
            "oy-qr\n" +
            "ow-rz\n" +
            "hy-lx\n" +
            "ii-bt\n" +
            "by-rb\n" +
            "fs-kq\n" +
            "ih-hk\n" +
            "oa-hk\n" +
            "mx-el\n" +
            "pj-uv\n" +
            "tt-ey\n" +
            "cy-uu\n" +
            "nh-nx\n" +
            "ql-hw\n" +
            "cl-ct\n" +
            "se-zf\n" +
            "qu-ja\n" +
            "bw-bg\n" +
            "jh-aa\n" +
            "ft-xn\n" +
            "xg-ff\n" +
            "cx-zx\n" +
            "jb-eo\n" +
            "kc-es\n" +
            "bi-es\n" +
            "ms-wo\n" +
            "eu-mh\n" +
            "wc-um\n" +
            "fn-sw\n" +
            "ca-lv\n" +
            "yo-cy\n" +
            "rt-xg\n" +
            "vt-ey\n" +
            "xd-vn\n" +
            "hz-vp\n" +
            "dh-cx\n" +
            "kj-kl\n" +
            "zb-cj\n" +
            "la-ac\n" +
            "wz-ma\n" +
            "eo-fn\n" +
            "jh-iu\n" +
            "om-as\n" +
            "td-qe\n" +
            "fz-wj\n" +
            "so-gk\n" +
            "ij-ls\n" +
            "id-ni\n" +
            "il-xx\n" +
            "dr-wl\n" +
            "xe-va\n" +
            "cj-dr\n" +
            "et-br\n" +
            "iu-qr\n" +
            "pi-em\n" +
            "kh-zv\n" +
            "qi-df\n" +
            "ey-hh\n" +
            "ls-dl\n" +
            "xo-qe\n" +
            "ly-ur\n" +
            "od-ds\n" +
            "zf-lr\n" +
            "vi-ep\n" +
            "lv-ol\n" +
            "bu-br\n" +
            "du-ir\n" +
            "pj-zt\n" +
            "hh-eb\n" +
            "aw-dx\n" +
            "gy-ob\n" +
            "ms-re\n" +
            "dn-no\n" +
            "tt-bh\n" +
            "bh-lw\n" +
            "xx-af\n" +
            "of-dq\n" +
            "bm-pv\n" +
            "ny-vk\n" +
            "ek-vr\n" +
            "fq-ur\n" +
            "hf-sg\n" +
            "vm-dg\n" +
            "dl-ph\n" +
            "go-wn\n" +
            "cn-fg\n" +
            "sy-lt\n" +
            "fu-nw\n" +
            "sx-zy\n" +
            "vw-za\n" +
            "ro-gu\n" +
            "jv-fs\n" +
            "hv-ap\n" +
            "ma-xn\n" +
            "db-ir\n" +
            "ms-nw\n" +
            "ty-lu\n" +
            "nv-kv\n" +
            "my-gx\n" +
            "pb-ap\n" +
            "lk-vn\n" +
            "bp-er\n" +
            "bm-mz\n" +
            "vx-qg\n" +
            "ik-kv\n" +
            "ph-uq\n" +
            "zp-qb\n" +
            "hm-dy\n" +
            "hj-gz\n" +
            "nn-kg\n" +
            "gw-ol\n" +
            "jw-wa\n" +
            "cq-hi\n" +
            "lr-mh\n" +
            "ns-ij\n" +
            "kt-dd\n" +
            "ge-bz\n" +
            "zn-hi\n" +
            "fg-vi\n" +
            "cf-xy\n" +
            "dx-ny\n" +
            "kl-bp\n" +
            "gj-cv\n" +
            "eo-xw\n" +
            "om-gu\n" +
            "nh-vk\n" +
            "ii-bw\n" +
            "zf-un\n" +
            "nf-rr\n" +
            "uy-ou\n" +
            "zc-qs\n" +
            "yo-uu\n" +
            "qd-lw\n" +
            "lq-ub\n" +
            "bd-gl\n" +
            "rv-qx\n" +
            "md-gn\n" +
            "uu-ps\n" +
            "qb-mg\n" +
            "nm-uj\n" +
            "rn-fd\n" +
            "po-eo\n" +
            "vp-zn\n" +
            "tn-xg\n" +
            "fm-dw\n" +
            "as-zx\n" +
            "uk-px\n" +
            "fa-nl\n" +
            "lu-wr\n" +
            "nx-aw\n" +
            "sk-nl\n" +
            "fq-gl\n" +
            "uu-qp\n" +
            "kv-bx\n" +
            "tt-vt\n" +
            "in-fu\n" +
            "kd-pz\n" +
            "ok-nc\n" +
            "xx-ln\n" +
            "ia-sp\n" +
            "yn-ra\n" +
            "eg-ec\n" +
            "bb-en\n" +
            "aw-qo\n" +
            "qx-ro\n" +
            "ue-kd\n" +
            "as-dh\n" +
            "ps-jl\n" +
            "vz-my\n" +
            "xq-ae\n" +
            "vz-mn\n" +
            "gf-op\n" +
            "td-pf\n" +
            "cs-qw\n" +
            "ns-og\n" +
            "ou-qx\n" +
            "ls-ns\n" +
            "wo-mh\n" +
            "cl-jv\n" +
            "yf-eg\n" +
            "yp-ry\n" +
            "kc-fe\n" +
            "iz-ju\n" +
            "vv-qb\n" +
            "le-vo\n" +
            "py-ex\n" +
            "zw-fl\n" +
            "zy-em\n" +
            "mb-dj\n" +
            "my-yt\n" +
            "oa-rj\n" +
            "ju-dl\n" +
            "xq-ou\n" +
            "jo-iz\n" +
            "ta-yb\n" +
            "yb-hf\n" +
            "xx-xl\n" +
            "xo-ku\n" +
            "mo-qa\n" +
            "kc-eq\n" +
            "bk-ac\n" +
            "pf-ws\n" +
            "jy-og\n" +
            "ut-bd\n" +
            "zh-yq\n" +
            "pz-xl\n" +
            "fi-fh\n" +
            "fl-fc\n" +
            "ig-cq\n" +
            "zp-ix\n" +
            "jt-vm\n" +
            "di-cn\n" +
            "tu-si\n" +
            "ew-ka\n" +
            "ig-zn\n" +
            "te-uv\n" +
            "ra-ca\n" +
            "he-gp\n" +
            "vc-rb\n" +
            "wb-gp\n" +
            "qr-gj\n" +
            "ia-zc\n" +
            "ai-ac\n" +
            "qm-fn\n" +
            "ca-kr\n" +
            "kv-hq\n" +
            "tq-rp\n" +
            "ji-bg\n" +
            "ho-lh\n" +
            "af-kd\n" +
            "fe-bi\n" +
            "tz-ty\n" +
            "bc-iz\n" +
            "bu-ti\n" +
            "mo-sw\n" +
            "oy-ij\n" +
            "qd-in\n" +
            "gf-xj\n" +
            "ui-gl\n" +
            "vv-tr\n" +
            "xm-mt\n" +
            "bo-ax\n" +
            "vd-fz\n" +
            "fi-lz\n" +
            "td-pl\n" +
            "gq-go\n" +
            "pp-ow\n" +
            "ap-qo\n" +
            "im-rj\n" +
            "mw-yi\n" +
            "yg-ly\n" +
            "jo-rp\n" +
            "ir-zw\n" +
            "wb-pj\n" +
            "cy-fp\n" +
            "ue-bh\n" +
            "na-qu\n" +
            "uv-zv\n" +
            "lz-la\n" +
            "is-el\n" +
            "nl-kq\n" +
            "au-mz\n" +
            "yq-la\n" +
            "dw-op\n" +
            "kj-fe\n" +
            "ii-ji\n" +
            "rt-so\n" +
            "eb-vt\n" +
            "ph-ij\n" +
            "iz-ph\n" +
            "op-mw\n" +
            "cp-fw\n" +
            "bv-dn\n" +
            "ys-ek\n" +
            "vv-nm\n" +
            "og-fu\n" +
            "lb-tu\n" +
            "ft-ma\n" +
            "kc-bj\n" +
            "zr-lk\n" +
            "gs-fa\n" +
            "hr-ca\n" +
            "hv-id\n" +
            "bc-rm\n" +
            "na-yt\n" +
            "tf-zn\n" +
            "nn-yh\n" +
            "hr-lf\n" +
            "ej-pv\n" +
            "gl-rk\n" +
            "ov-no\n" +
            "ge-qi\n" +
            "ex-gq\n" +
            "fk-si\n" +
            "fe-er\n" +
            "jw-nq\n" +
            "lx-md\n" +
            "he-we\n" +
            "gy-do\n" +
            "mw-tk\n" +
            "ke-cx\n" +
            "nq-zx\n" +
            "ih-yp\n" +
            "ib-pg\n" +
            "em-kg\n" +
            "sm-as\n" +
            "jt-lc\n" +
            "nh-ny\n" +
            "xp-mw\n" +
            "ca-eh\n" +
            "jz-hv\n" +
            "ab-at\n" +
            "bh-ai\n" +
            "qe-ov\n" +
            "xi-tk\n" +
            "ch-yw\n" +
            "hj-md\n" +
            "sa-lu\n" +
            "qo-pb\n" +
            "zv-wp\n" +
            "bo-xh\n" +
            "gs-cl\n" +
            "qy-ao\n" +
            "is-sw\n" +
            "uk-rq\n" +
            "kw-xq\n" +
            "cx-ro\n" +
            "ej-dz\n" +
            "qs-rf\n" +
            "yo-zq\n" +
            "yg-hs\n" +
            "dv-cn\n" +
            "oz-bb\n" +
            "ni-pb\n" +
            "db-py\n" +
            "aj-pq\n" +
            "wg-iz\n" +
            "ob-ok\n" +
            "sm-ke\n" +
            "gr-cp\n" +
            "uj-vv\n" +
            "xw-tj\n" +
            "in-hy\n" +
            "rr-nm\n" +
            "qk-fr\n" +
            "nm-tr\n" +
            "gp-af\n" +
            "af-vl\n" +
            "bs-rm\n" +
            "wd-bx\n" +
            "wq-um\n" +
            "wp-kh\n" +
            "hu-ff\n" +
            "cb-ha\n" +
            "rp-eo\n" +
            "ox-uq\n" +
            "jv-ct\n" +
            "kg-yh\n" +
            "ih-vz\n" +
            "dv-xm\n" +
            "cf-gj\n" +
            "wc-xh\n" +
            "ti-gr\n" +
            "cq-vp\n" +
            "cy-qk\n" +
            "yi-xi\n" +
            "hx-de\n" +
            "ao-vh\n" +
            "jd-ue\n" +
            "md-mq\n" +
            "ey-bh\n" +
            "ns-uq\n" +
            "uu-jl\n" +
            "af-dd\n" +
            "xx-kt\n" +
            "zq-cy\n" +
            "ub-qd\n" +
            "ql-yq\n" +
            "kj-bp\n" +
            "at-bv\n" +
            "dh-zx\n" +
            "kq-cs\n" +
            "sn-xh\n" +
            "gz-oz\n" +
            "bk-vt\n" +
            "oo-ke\n" +
            "qp-qk\n" +
            "vl-kd\n" +
            "rp-jb\n" +
            "eg-dk\n" +
            "rb-bg\n" +
            "mi-iz\n" +
            "wp-we\n" +
            "bc-wg\n" +
            "ju-ns\n" +
            "kn-ez\n" +
            "gf-xi\n" +
            "xw-po\n" +
            "fz-df\n" +
            "av-ce\n" +
            "ls-iz\n" +
            "lk-np\n" +
            "px-de\n" +
            "um-rg\n" +
            "kv-mb\n" +
            "tz-lu\n" +
            "jb-vc\n" +
            "gg-pp\n" +
            "qq-rj\n" +
            "dg-lt\n" +
            "wb-uv\n" +
            "ut-tx\n" +
            "vj-qp\n" +
            "dd-il\n" +
            "ir-vs\n" +
            "wd-kv\n" +
            "cf-zb\n" +
            "fn-tq\n" +
            "nt-ok\n" +
            "tf-ig\n" +
            "eb-bk\n" +
            "cy-vj\n" +
            "nh-aw\n" +
            "zb-jh\n" +
            "bg-ta\n" +
            "zf-wv\n" +
            "sd-sz\n" +
            "yk-ty\n" +
            "sb-qi\n" +
            "vz-lj\n" +
            "ma-vb\n" +
            "bd-cb\n" +
            "sa-pr\n" +
            "nv-wd\n" +
            "vz-hk\n" +
            "go-od\n" +
            "ko-ec\n" +
            "cs-fs\n" +
            "ih-my\n" +
            "ya-pl\n" +
            "xo-mg\n" +
            "bm-oa\n" +
            "od-gq\n" +
            "id-pb\n" +
            "ko-dk\n" +
            "vc-nj\n" +
            "uf-de\n" +
            "ft-yc\n" +
            "mb-kn\n" +
            "ew-of\n" +
            "za-oq\n" +
            "qb-uj\n" +
            "vv-rr\n" +
            "yc-xn\n" +
            "nj-ta\n" +
            "tf-vb\n" +
            "xk-un\n" +
            "hr-pw\n" +
            "hg-ca\n" +
            "yw-bu\n" +
            "mb-cr\n" +
            "oq-qs\n" +
            "gj-zb\n" +
            "an-re\n" +
            "uf-so\n" +
            "dj-bx\n" +
            "rz-vq\n" +
            "qx-wc\n" +
            "gv-tr\n" +
            "lz-qn\n" +
            "nv-kn\n" +
            "vx-hm\n" +
            "wu-ym\n" +
            "jd-kd\n" +
            "vc-by\n" +
            "aa-cf\n" +
            "fq-cb\n" +
            "ow-ha\n" +
            "nh-ap\n" +
            "nl-sq\n" +
            "fc-sa\n" +
            "gv-oi\n" +
            "nt-ss\n" +
            "op-xi\n" +
            "jk-iy\n" +
            "oi-nf\n" +
            "cm-ho\n" +
            "aj-jn\n" +
            "gu-zx\n" +
            "zr-ka\n" +
            "mt-ho\n" +
            "ev-ya\n" +
            "lz-ec\n" +
            "yx-lc\n" +
            "eh-dq\n" +
            "of-np\n" +
            "wi-so\n" +
            "hi-tf\n" +
            "xl-is\n" +
            "yb-rb\n" +
            "sk-gs\n" +
            "zv-cg\n" +
            "hs-ma\n" +
            "ys-pg\n" +
            "dl-mi\n" +
            "ez-mb\n" +
            "ex-an\n" +
            "yo-ps\n" +
            "ir-ds\n" +
            "vw-qs\n" +
            "um-rv\n" +
            "tr-rb\n" +
            "ex-hw\n" +
            "jv-cs\n" +
            "ab-sz\n" +
            "yc-wz\n" +
            "ap-bm\n" +
            "wa-ha\n" +
            "wb-he\n" +
            "sn-rz\n" +
            "gw-ho\n" +
            "wz-xn\n" +
            "il-hm\n" +
            "bb-md\n" +
            "dz-sd\n" +
            "tg-oi\n" +
            "od-py\n" +
            "hh-ac\n" +
            "lj-ae\n" +
            "dj-cr\n" +
            "oe-cm\n" +
            "by-hf\n" +
            "uk-aw\n" +
            "di-xm\n" +
            "ph-bc\n" +
            "qs-za\n" +
            "it-ui\n" +
            "qy-va\n" +
            "fw-gr\n" +
            "qn-zh\n" +
            "ub-wl\n" +
            "om-gx\n" +
            "jr-th\n" +
            "la-zh\n" +
            "fr-yo\n" +
            "dw-tk\n" +
            "gj-xr\n" +
            "bm-ej\n" +
            "tm-ow";

    public static Input getData() {
        return new Input(trueData);
    }
}
