import Library.Quadruplet;
import Management.Input;

public class Inputs {
    public static final int phase = 2;

    // Sample data
    // A: Sample input
    // B: Phase 1 expected output
    // C: Phase 2 expected output
    // D: To print or not to print
    public static final Quadruplet<String, Object, Object, Boolean>[] samples = new Quadruplet[]{
            new Quadruplet<>(
                    "r, wr, b, g, bwu, rb, gb, br\n" +
                            "brwrr\n" +
                            "bggr\n" +
                            "gbbr\n" +
                            "rrbgbr\n" +
                            "ubwu\n" +
                            "bwurrg\n" +
                            "brgr\n" +
                            "bbrgwb"
                    , (Object) 6L
                    , (Object) 16L
                    , (Boolean) false
            ),
            new Quadruplet<>(
                    ""
                    , (Object) null
                    , (Object) null
                    , (Boolean) false
            ),
            new Quadruplet<>(
                    ""
                    , (Object) null
                    , (Object) null
                    , (Boolean) false
            ),
    };
    // Puzzle data
    public static final long[] tooLow1  = new long[] {};
    public static final long[] tooHigh1 = new long[] {400L};
    public static final long[] tooLow2  = new long[] {};
    public static final long[] tooHigh2 = new long[] {};
    public static final boolean printTrueData = false;
    public static final String trueData = "wrgrwbug, uurb, rbubr, buggb, uuwwwrb, gg, wgburr, ubg, wrbuw, grrr, rur, ggb, bur, guwggg, rwbr, grurb, bgurguw, ruub, uguugg, bwr, brggb, rwuu, rrgbuw, bgub, wbbb, rgg, ubrgb, wbrgw, rgwwuww, b, buw, grb, rww, grurw, ggwb, rbw, brbw, gb, gwwr, bugwrg, uwbww, ggu, bbbbbbur, gu, ruurw, uwr, gbur, gbgbu, wrwru, urrr, bruu, wbbgrg, gwrwr, brru, buub, wrbb, wrb, urugbur, bgwwr, bwubb, wrbbbbbb, gggbgur, www, rbuuggr, rrruwguu, wgr, r, ggw, wb, gbgr, bwbu, wgwuugug, uuug, grgw, gbbuwrb, ug, gub, wbrbug, wrrgrr, rbuu, rrg, brbu, ugwu, bguw, guww, ugw, wwg, ugrb, ggrw, uug, uww, bbw, bwrw, urr, bwbuw, rbugr, uubbwu, rru, rbb, wbb, wguu, urb, rwbrubb, rrgru, ugg, rgw, gwbb, rbrr, gbwg, wgrb, wbbbbbug, u, bru, uububwwr, wburugg, wrgugg, urgu, uuuwg, grbuwwb, brg, grwubr, wbrww, bugu, wgwrbwu, urrbr, w, wubwu, gbgugw, ggrbwr, ugurrr, ubrgu, bggrb, gugwb, rw, uuwg, wguw, wuru, rugu, ubgru, bgubr, urww, buggg, wwb, gwbu, rgbbbb, burrw, ugbuwr, uwbw, bug, urbwgwbu, gubwuur, wbgrbb, wub, bb, ugbgwr, gwbww, gggbw, bggg, gbwbur, wggg, ruuug, grw, rwg, wguwbr, rggr, wugw, rbwb, ru, wrbur, gug, rbru, buuubwb, gbwgug, ggubu, buwbwr, gru, wuw, wbg, wbr, ubgw, brwugb, rbwugr, rb, wbur, rr, wbwubuwr, wuggrb, bww, ruw, rbu, wrbrr, ubwrrwbb, guu, brb, rgrr, wgg, bgr, ggruug, bgug, ugwug, rwrrb, grbg, bbr, ugrbbrgr, gwbg, wbwgw, wbbrrb, wwgw, rwrg, wrrugr, wg, rgrwwbg, guw, urg, uugbg, wwbw, ubr, rurb, gugg, wgu, rguug, rwb, wrr, ggbwuu, gw, uuwrwu, gbbugr, rwwrwubr, uwwwgg, uur, uuu, wug, gwrrg, gwu, gwurg, bwrugr, bgb, grr, wuuug, bgw, ubwr, bwbugb, rgwrwg, wruwgru, bbu, ugbuwgu, rbr, ugrw, bugub, rwuuw, grbbuwgr, wbu, gwb, guwwurwr, gbbub, wbrg, bgrbw, urggurw, ruu, wuu, wruu, gbwb, bgwug, rurr, ubuwgw, bwugggb, gurgb, rbbwrgru, bbrb, bubu, bbur, rgb, rbrwr, bbb, bwugr, ggr, wwub, ugrwbrw, rugg, rrrwu, wbgrr, wuwrr, rgu, gbb, bwuw, wbuwrrgb, bwwrgu, ururwubr, rrbwwuw, rwrwb, bwruub, wgrrg, brr, ur, uw, bbg, wbwwr, brur, wruwbb, wwr, wwu, uuwb, ggurb, uub, rrb, rbwr, rbbbb, rg, rgubbb, ubbgruwr, wwwgu, bwgbrrw, wbw, gbguu, wgwr, grurbur, wuburuu, rwgrgr, wur, bwb, wgw, rwr, ururb, gur, rrgwww, bw, ubgbru, rbwbgrb, wrbrb, wubw, wgbub, wrg, rrw, brbr, ugu, guuuugb, wurbgwgg, uurbbgw, urw, rurg, ubw, wgbu, rwguu, gbu, ubuuw, wubruru, bwg, wuuuu, wu, wuuu, bwru, uruu, gwr, bgu, wrgr, ggrugbg, bwgu, ggg, wwwgb, rgru, wbgbu, gr, ubu, guubwu, rgwuwug, bwwru, bub, gbuu, guwbwur, gubrurw, bwrbuwr, wrw, rrrrrg, rwu, gubbuu, uru, uwbg, rurru, rrwwbb, ubgb, rgwugg, buu, ggwwbr, uwg, bbwrgu, ww, urbgbbg, uggbrww, gwg, wbrr, rbrb, ruuwgr, guubrg, uwbbb, rbg, bbgru, gbw, rwrrg, ubrwr, ugb, uubgwru, buwbuwu, wbuww, rrbr, rwbw, ggwr, grrwrg, gbrgwu, bbbu, uwub, ubb, gwur, brbruug, gww, wwugbw, rwuggw, bbrbr, rrr, rbgggw, rug, ggrrbr, brrbb, uwu, ruwwr, rgr, br, rgrubgg, ugr, wgb, wwwr, ggrbbb, uu, gubgwgb, rwbgbr, wru, wgww, rub, uuw, rwubrruu, grg, brwguug, guguu, ub, bgg, wuwu, wr, bwbg\n" +
            "rwuugrgubgwgbrrurggwbugbuuwgbugbuwwwubbwbbw\n" +
            "rubgrugwuwburwwrrrwggrrrbbwwwwwuwuggururgrurgwbwwwugwwggur\n" +
            "wrgrrgbbgwuwguruurwbgurgubgbwuwwwuburggbwggwrwwggbg\n" +
            "uwwgruguubwbbgurubbuwggwuuwrrbwuugubgwuwbbggwggbbrurwu\n" +
            "ububrgrburwrrbbbugrubrugrugrwwbwguwggwrrrurwwuuubgwwbbbb\n" +
            "gwrwugubugrwgrrrgrwbburgbbrgrbuwwgrggubbugugwuwbww\n" +
            "uwgwwrbwwurbrbburubbrubrguwbugbbbbugruurgugwurgwurburrbwrr\n" +
            "gggbugbwuuwbubwuwgwuggurwrgbbbuuwuggwbugugwr\n" +
            "ruwburwgbuguwbbuuggrwgrgbbugubgrggrbuwgrbrubwguwgubrubggbg\n" +
            "bgwgwubrwggwgbuwbuurgugurbburbburuwgwwwbrubrrrgrgbrgwwwrug\n" +
            "wbgurwwrrwgwrugwbgwbbrurgurrbgwwwurbwgrubgbg\n" +
            "brwwgbguubrgwguwwuuwbwuwgrbrrbrrgubgrgwuwugbg\n" +
            "buuwugbuurwugurugubrwburruwgrgwggbubwgwuwbrwguuugb\n" +
            "rrwugbwbgggguburuuuuwwrgubugrwwugwbgbggugrrrurugwwugrr\n" +
            "ubbgbrwgrrwrwrbuwwbbguguuwgwruwbbwgrgggbrbgwggwbwurwuuub\n" +
            "wrbgwwuwbbwbgubrbubrbwwwuwbguwgwguggbgbrburugbg\n" +
            "ggwuwwggwwgbgrbrggbguwrwbgguwggbbgrrwbbgwwuwwbwgrwwgbg\n" +
            "ggwwuggggbbugggggubruuugbrurwgbrbrwrgbwggrr\n" +
            "gggbwuwwbugwurwrbruugwgrbrugrggbgrwgugwruu\n" +
            "bggrgrgbrwrruruguuuwwwgurbrrrgwbubbwrrrbggugrbbrgrwg\n" +
            "ubrugrrrwwwrbbrwuwuuuwwguurbwrrggguugugubbwwgbg\n" +
            "rwrrgrwrguubgrbrbbggbwgruwbbgggwgrgrwbuggubwurwwbgbrubwgbg\n" +
            "buguwuuuruwgggwwbggguuwguurrruwwbugugbgbg\n" +
            "wguwwwrwwugggbuwubwurrbubwggwwrgggbgguruwbb\n" +
            "ggrwbwrugbuwgrbburugwgbgwrbbgrwuwbrwrrrrrbgbrbrwu\n" +
            "ggrggbgbrwrbuwgggwgubbgurbuwuwrurwbwrrruugggggurwrbggbg\n" +
            "bbbgrggbwrrwubgwrguuruwbwurrbrwrugubwwgugububggwrbb\n" +
            "ubwbrurggrwgrwuurgugruuguggwubuwbrrwuwrwrbgurrbrggbwru\n" +
            "ubbrggguwguwugurwgubwwbugrgbguuuwbbuubrbrwruburbbguug\n" +
            "ruwgbbuggwrrrbrruwrgrruurwgbugbgbubguuwguurwgubuwr\n" +
            "uwburgrwuuwwrrrbguurbbuuwrbbggbuggbwugbbuuuuwwggrrr\n" +
            "ugbwwgwuwurrbrbbbugwgbrrrrguwuwguwurugbg\n" +
            "ggrrwuubrurrbbwubrbrugrggbrwbgruwgbwwuugguwrwubuwrwrbgbg\n" +
            "buwgggwgguwrrurrwruuubbwgrgrgbwbgbbwwwugbubgbg\n" +
            "wwgggrbuuugubwurbgugrbrwrggwwgruubwrbbuuuwgbg\n" +
            "wrrrurruuwgwrbwbbgbrbbwrbrgbruuuwubgubgbg\n" +
            "bwgugbrruuwrrwbwwwgbwrwgbrwrguwbggugwbgubgwbu\n" +
            "grrrgbggwbgggbbwbbuburrubrguguuurrgwrbwrugrwububgwrrgbg\n" +
            "urbggrugbgruguwbwurbugbuwgwwwbuugurwguugrrbwgurbgbg\n" +
            "uwwrubrugwrrruwguubuwwruuuwurwuwgbbwbgbgwbuggbgubg\n" +
            "rugbrrgwwubgwbgbgwuwwwugwwubbwuwgwuuruguuwubwrbggbggwugbg\n" +
            "uubbwgbrwwgbggugbbrguggbwuwbgrbgrgurrurwwuwbrrwggggwgbgb\n" +
            "rbuuggguruwrbbgbwbbrbbuuwwgurbrrwbrrubwgbgwgrguurbubbrwrgbg\n" +
            "bguuwubrbgurguurgwbuwgbrbubwwgbbwuubwugbwbuuuug\n" +
            "rbwwrgrwbugbrrggwbwbwwwrwwggubuwrrgrbwwbggrrrwgwwb\n" +
            "ugggwgbbrrwgwgurubbbwgrbbwgguwwggrburgbuuuwuwrrwgwbwggwrb\n" +
            "rbwrbgwwrwrugrburwuwbwgruuururbwbbggbbgbgggbg\n" +
            "ugwrbwbrbgwggwggwguwwrwgbgwruwurggwwrwbgwgrguubbg\n" +
            "guwgbwrgwrurubwbgrwwrgurwbgubbrwbbrwbwwgguwrggwwrwuwr\n" +
            "grrbwruggugrgbwuurggugbguuwburgbbrgguggwubg\n" +
            "brbrggrgwguwwrgguuuwwurgbrrbwwwwwrbwwwurgrgubruwbwggurgrg\n" +
            "bburrurbgwguwuguguwgwruwrggbwubuwwubgwrurwrbrrbbbrgr\n" +
            "gruwguwrurwrwgwwgwbggugbbubbbwuwbguwbubrgrbrrgwbu\n" +
            "brbbwbbguggwbrurrbrbuwgwuwwgugwwbubruurwuuuggg\n" +
            "uwrbggggwwbgrrgbrurgbgugubrrubrgwrrbggrrbbgbrrbgbubggbg\n" +
            "wggbgwrwwruurrruugwgurgbrbwwgbbgbubwgbwbgrb\n" +
            "wbuuugrbgurbrugrruwwruggubrugrububwwbbwgbwrrbguwugrwuggbg\n" +
            "rwurgbgwrbubbwbgrwwruggrbguuwuwugbwurrgurrburg\n" +
            "rrggggbgggurwrgubwgbbwwugwguuubwrrwbbugruwrugbugurgwwwbb\n" +
            "uuwrrrwruwwubwrbbwwurugurbbuwwurbruwrgwgrguwrwrrwwrgrwbugbg\n" +
            "guuwugububrggurgwwugbwrwuubrbugrrbwubrwugbg\n" +
            "wgrbwwuwwbgwbuugubwuwbwguggbwuwrgbbwbwwrugr\n" +
            "urrrwrwbwuwgwrwgburruggbwuwggrwwbwgbwrwggwbrugggr\n" +
            "rgbwubrrwwwubbgwwurbugbrrbggbrugrwgbrugbg\n" +
            "ggwbwbubbgruwrrwbgrwrwgwuwgggwrubrwrubgbwwwbbrr\n" +
            "rbuwrrwggrgwubbrwwrwrbbbbbburbuwuruwgwgbwrurwgbg\n" +
            "uwbrbbrbrbwgggwuguwgugurgrrrwwurrwbuwruurrwgwbrburrrwug\n" +
            "urguwrrgbwwwubrbuwrguubggbrrrgbwrbbrgggruuubbgrrgugugwgu\n" +
            "rwrbrwurrrrwwgbwbwbwgbgggubbubggguwruuuwbrbguwrwugwr\n" +
            "rrwrrwbwwbuwbbwugwbbguuwbwbubgrgubgrrrbgwuuggwrrbbrgb\n" +
            "uwrgrrbbbruwgrbbrgwrwuguwrbrggwbbubgruggrgbg\n" +
            "uguugugwwubuugrrbwubrrrwrwgbgbbbgwwrbbrbgbg\n" +
            "bwwuruuwburbruwwrgbbwruwurgrrrbrbuggubrbbubgbrbgwgrruuubw\n" +
            "rrugubuwrggwrgbrrbuurbbwgbguguggggrbuwwgggwburbgbg\n" +
            "grwgburuwwwgwwrgwwgwrwgwugubrgrwuubwwuwggrwwrwgur\n" +
            "ruwugugbuggwwwgurugrbbrgrubrrrrrwgwwwugbg\n" +
            "rruwwrrwrbwugbwwguwurggruuurbbwggggggrwuugbgwg\n" +
            "ububuubbggurbuwwwrrgbuurbuggrgbrwwgggwgwwrgrwuwggbguugbw\n" +
            "wruwrwggbbuuwgwbuurburuguwwgbrguwgwuuurggbg\n" +
            "bwbbgwrbrbgrrbgbguuruwugwuubuguggrbguruwrruuugubgruwggbg\n" +
            "gwurgbwrgbgwrwbgbbgugbrwuuwggrggurbbgubrrugubwubrrwrgw\n" +
            "urbbuuuuurrbgrbbbbbburrggwrrbwrrgbwwwwwuggwwwwwbuuubuugw\n" +
            "gbggrwugbwrbuwrbubuugrbrubbgwgrubbgbwuuurrbrwgrrbwbb\n" +
            "rrwurbwrwurwuugbgbgbwbbbuuubgwwgurgwgubwgbg\n" +
            "ugrbwwbuuurubbrgbubwgbuuwbgwuwuugggwgbuwugrgubwgrwggbgbg\n" +
            "rgbrgbbguruubrgrbwwbbbwubgubgwgrwwgggguwrrbrurbgwrrggw\n" +
            "bwbburbgbwgrurgwrrguburrbwwuwrwrrbbubgwruuwwugbg\n" +
            "uwrbwwrrbrbbbrrbbbbbburugugbburugggbwuggbgbgwbwwbuuubbgbg\n" +
            "rugwgbrwgwuwubwwuwgbrgwggugubwugwrrwgruwbbgrgbg\n" +
            "rbrgrguuubgwwwugrrwrbrruuwgrgugubgwbuubwrrwbbbrrwbbgbg\n" +
            "rbgruwbggwbwgwgbrwurbwgbguggrwbrbwwuuwggbugguggggrwubrbuw\n" +
            "gwbwurrwuwgwgrrbrgbuuwrrgrwwuurrwrrburuwuub\n" +
            "wgwugugrwgbrbugbgurrwggbgrubwggrbuuuuwgbg\n" +
            "wguggbuguwuwrbwbrwgguwrgbwgbgrwruggurguubgruwbbugwwug\n" +
            "gwuwbbgburrrwbgrbwuguwubwuwruggrbuuuwruuwrrg\n" +
            "gwrwwrubrruwuwubrggwbrbubbbgrurwwrbgwgrgrbbwwwbgbrwugw\n" +
            "ruggruuuwbgbbwwurrwruwrbwbwubuwrbrbgbrwuggurwwwurw\n" +
            "rwrwbuugurwwuwwruguubbbwwwwgbrurububrbubwg\n" +
            "rrrrbgrwgrwurgwrbbwurbwgwbuguuggwrgbrwrwuuwwrrbgbg\n" +
            "ggrwgbgwubwbrrgruuubgwgggwwwrbgbugwrurggrbrg\n" +
            "buuwggubguwbgrbbggbwwurbwgwggwwrwurwbwubbbbu\n" +
            "ubwgbbwggrgwrrgbrgwwwrwrgguwubrbbrrurgrwuggurgbwwrwur\n" +
            "bggrrggrrrbuburwugguubbburgrbgurgurrwbruuwbrrwrwbrgrurw\n" +
            "wgrwrgrrwurgwgbruwugbuggbbwrurrgbrrwrwubgurrr\n" +
            "wwgwurubbbrrrurubwbbrubwrruwrbbwwwgbbbrburubuu\n" +
            "uguwwuguguwrwwuuuggbgrugubrggwurrrruwubbbgbrg\n" +
            "gubuwgwwgruububwwrrwbrbrwubbwrgwgrrgrwgbg\n" +
            "gwwwugwbwwugrwbwbrubuwwbrrwuwwgbrurbrwbrbbrwguwrrwwbbug\n" +
            "gbbrwwuwgrbuuuuuwbwbbbuuwrrrgggguwwwwwbgwwubgbg\n" +
            "wrbbbbugbuurwuuggggbrrurggrrgwggwgwgguuggbrrrgguuwurbrwrbw\n" +
            "rgrbuuuuuwrgwbbrugbuugububbwwwgbubuwbrurbuwwwrr\n" +
            "uuubrwbwbrgwubgbgwrruuuurugrgbwgbrrggruggrwuwwbrwgbg\n" +
            "gwgugubbwrrwgrburguwbgbbwggugbugwwruwwbgwwrwgubwruwb\n" +
            "wrwwgbwuwbbrwrrbbuurbbwrbubwrbwwugwrgbrubbgr\n" +
            "wgrgwbrrugwuwuurwrbgurbrrrbubuubwgrrruwurbrrgbug\n" +
            "bbrurgrgwwubgbbrwrruwbuuwgrbrrrrruwubbwgwgggbgruuggbg\n" +
            "brbrgburbrburugururrrrruwwbuurbwgrruuwwgbbuwwuugwwgwgbgrgg\n" +
            "uubrurrrubrgrwwwwwububggrggbuggurbbwrbuwbburbugrgwb\n" +
            "rrbbrbbwubrggbgrwbwgwgwugwgwgbbbwurwrgggrurgwurwbrrgrgbw\n" +
            "wwgbuuwruguuwwbwruuwggbbgwwguuurrwwbrurruuguubub\n" +
            "ggwbrggwuwwuwbbguguuggrugwbggugggrrrburguburbwbwrguwgw\n" +
            "buruubbruwrwbwgruwwuwrbuuwugrbrrrwgugrgggbruguwubbrurwb\n" +
            "wwrubbwggrwbuwrrurbbrrwurugbbwgrbwgubrrwwgwrgbg\n" +
            "rbguuwugrgruwbbbwruuurrgggrwwruggruuuurwuwrbgwggg\n" +
            "gbrrubbwurgwrwgubuubruwrbugbrwugwugbgbwgrggwgbbuubgwrb\n" +
            "bubwrwwgurrurubwbubrwuwuggwgrgwrrbwgwbwrrgrrbb\n" +
            "rrubuwbbruuggburwuugwwuubuwwuwurbgwgggwrwrgr\n" +
            "grgggubrgwbwwgggbwrwwrwgrguuwubgwuurgbrurgwgbg\n" +
            "brrbgrbwwuwrwuwwuwwgwrgugwgwugbgguwbbgurrgrwwuwgwubrbb\n" +
            "wrbbwgwgwwurbrrgguwbgwwwwbwwwrwwguggbuugugggubwubrug\n" +
            "rbbgubgwwruubgguwbwruubugruwuwbgwuugwgbg\n" +
            "wwgbuwuuuuugbrugrubgguuwrbgwruggrugbbbguggrburgubwub\n" +
            "buwugbwwrbgbbuugbgwwwuwgugbbubwugwbrrgubggwbrgrbbbrurwuwbu\n" +
            "bwruggrbwgggbugrgurrwurbrgbbgbbwgrwwrgruuwbbbgbuwrgbwuguggbg\n" +
            "wrruwrwwguwrgrggggwburbuubrrwwbruwgrwbbruwgwwggruwwgbgubg\n" +
            "bbbbrguruwrbruuubrwrwurbbbwwbguwwwgrrwgwbgbg\n" +
            "gbwurggbgwbbwruuggggruwurbbubwbrburgwbrbuuuubgbwgggw\n" +
            "rwbrbwgwwubrrrurrrubwbuwubgruguwgrwbggrwwrwubruugrbrggbg\n" +
            "ruurwgubuugwwggrrgrrwbgrbgwuburgugbwgrgurrgw\n" +
            "rrrrubbwbggrgrrbrrwbrbgrgrbgububgrbrbwbubuwrwbwugrgr\n" +
            "rbgwruruuuwrgwwwurrguurubrbburubbbggwwwrbgruwbgbg\n" +
            "ugwugurgwuuuuwguwgbugwgwggbgugrurwuwuurgwrgbgbbwuwuggbg\n" +
            "bwbrggwrbwbbubrbwwbbbgbrubwwrwbbrwubrruurwbbruugbugubwurgw\n" +
            "urggrbgwruurwrguuugrgwubgrbuwgwruwwwbugwuwg\n" +
            "bbuggwubwbggwwbgggwbbgbgbguuurbuwrgggbgbg\n" +
            "gwgugrwgrugrwrbrbgwuubrbbuurrgwwgbbruuwbwbuw\n" +
            "grgugwuwbgguwwwwrrwguurwgwruwgububbrbrggbg\n" +
            "uubugugwbrgububgrgbrwrwbrggbgrbbwrgrububwww\n" +
            "bgwurbwwgrwbwgrwwuguuwrrwrwruruggwgwgwbbbgbugbgbbbgbg\n" +
            "rbwrrggrguurgugwbwuurwwruwugburwrbruuugbuggrbbguu\n" +
            "wgrwgwgbbrgbwuwgbgrwrbbwwbgwrrwgwuuuugruuwwguguww\n" +
            "rugwwbwgwwbuwugrbwrbuwrwuuuggurbwruwguuuwruwwrgrbgbrubgugb\n" +
            "grbwrbbwwubgwbrbbbuurwuugbrwbwbgubbubrwbbwgwgbwwbbuu\n" +
            "rrugbrgrwwrwubrrrggrbrbruugwruuwrwrrwrggruwr\n" +
            "bburubrwuubwuwgubwbuubwbuubrwwggugbrrrurrbgbgbbbubbbwwr\n" +
            "buuurwwbuubgrruuurrwwwgwwwgwgwbgubwbrrbgwurbubwuruguubgg\n" +
            "rbwbrwwubrwururwubrbbgubrrbwwugbuurruwguugrwbbg\n" +
            "ubwwrbrruwwrwubgwrruwggbgwbggugururrugrrwwwuw\n" +
            "rbrwwwbwwgwguwgrgwurgrwububbrgwwuwugbuuuuggbgrbwwrgugur\n" +
            "bgwrbrrwrgrgrrbrwwugrrbubbrgwrwrrrguwwrbggrrw\n" +
            "uwwwrbwbrugrrbubugbbgwbwuubbrrgwrbbbbbbbrgbrwbrbuu\n" +
            "grgrbwugurggbwgwgbbgbbbrgbwgubrwbrgrrrrbwgrubwg\n" +
            "ugrbbuwbgwugbrwwuurrwwbbugruubwgbgwgrbwgbwu\n" +
            "uuwbgbugwrbuggwbbbugbgbwgrgbwguwbrbwrurwwuubggubrugrrr\n" +
            "grgggugbgububgwbgrgwgwbrrgruwrbubgrgrburwwrrug\n" +
            "gruwggbbugbgwwbbruwurbbrbrwwbrrwrrruwbwwggbgburggub\n" +
            "rgbbrrbrwuurubrwwgrguuwburrbbwruwbwrgrggbg\n" +
            "ubrwrwuubwgrruuurgrbgwwwrgrggwruuurrrwbrrrrbb\n" +
            "ggrbbbbuugrgbguurrgrgwgwburrrgwbgubggrwurwguwwgwrwbwrbruug\n" +
            "grrwrwwuugrggwbbwwwwurwbwbbbbgwgwrwburrugbbg\n" +
            "bwbgrurrwwgurwrwurgwwwbbwgrurwburbuwwuuggrgbrubrgwurbubu\n" +
            "urbrrwwbwwbwgbuwruuurrrbwbwrrrwgwrbuuwurbbuugr\n" +
            "uubrbgbubbrrubwrguggbubuwrgwgrggurguuwbrwgwgwwugwbbww\n" +
            "brgbwrbrwwwbrugguuwwwbgbgbgrurwuubbbgwgrugbg\n" +
            "ubbggrrububwbuuwbuwwggrurrugbguwwrgbbgbwwbbg\n" +
            "uubguburggrgggurwrwgbuggrbwuuwwgbburbgbbwuugrwgwrggruuubr\n" +
            "bbbgggruubuuwbruguubgwbrbgwgbwruwbrwbwwwggwwwbur\n" +
            "rbrruburrugrrggurugbuuubuggrbbuwgrbwrwrrbwgburgggwwwuubr\n" +
            "urbrrbwgbgrrgrwwrrbwuuruwubwrbrwrwwruugruu\n" +
            "bbgrguuuwwrwbrugbwwugggwbbbbbugbrwrbwwgwrrwwrubwugrbgwgwrw\n" +
            "wbguggrrrwrrbwrbruwbgggwwbgurgrbuwwgwgururbrurubggrwwbuuwu\n" +
            "wrubrrwggrgggwgrgrbbgwbuwrbwwrugwwwwbwburgbgguruubb\n" +
            "urbugrgbgrbbuwbgbwbuwbwwgwbbrrgggwgrgbgwwrbubrgwbrwr\n" +
            "wurgwrrbbbwrburgbgrubgurugbwgrgburrwwbgwugurwuuuguwrbgrugbg\n" +
            "gbgubuuwgwrurbgrwuuurwbbwggrrwubrruuburugrbuuguuguuugugbg\n" +
            "gbrrbrbuurguwbuwrrgbrrbbgwgwggwbuwgrgrwbbwgb\n" +
            "bbrugrwgrwburbrbburrurgrbggwrbrwrbgwrrrgbrwrgwgugbggwr\n" +
            "wrguwbgbbrubuwwwurgurrurbwbwrrbbggbbgwrrwbuuwww\n" +
            "guuubgrwrwurgbrubbguubrgggwwbwwurggbrwuuwuwwbrwuwbburbwww\n" +
            "uwrubwgwuugbbbwburgbuubwbuwbwwbggwbbbgwwrbbru\n" +
            "rbuwgwwgbrgggrgrwwuurrwggwuwwbrbggwbggbrgbbg\n" +
            "wgwwugbrwurguwuwubugbwgbwurbuwwguubrbbbrgubwgrbrr\n" +
            "gbrburgrruwubwwuggggugrbgbbubbgwuwbuguwrbbrbubgwugbwrr\n" +
            "bgbbrrbuuwgbubrwwrgbgrwwwubrrrrrrbwuurbgwubbgruwrbwgbg\n" +
            "grwrrwwuwwguwgrugwwwrbgbuuugubrwwgrbwwgrbrru\n" +
            "grwwwrbgggbwggrbgbwwrwwwbgbbrgbwuuruwbbugbgbuuuubwbgwgbg\n" +
            "bgbgwrrwugbrbwuggurruurrwuurggrrrbwbwbubwwwbgugggbugwrwgbg\n" +
            "urgrbugrgwguwgwbgbbwbrgwbbwggbuurbrbwwgwwuwwuuwurbwwwrgbg\n" +
            "bgugrbubgwubwuggrrrugwgbgwrgggbwbuwbggrrubbugbg\n" +
            "guurubwrbggwbrubuuggubrugrrbbwuggwuggggubguububbbbgbwuwr\n" +
            "bggwrwwrbwggwgwuruwwbububbwgurwurubruwwuguwugrurwwubwrub\n" +
            "wbwurrrgrgrrwuubbwugrrwububbwwrwgwwwbuwuwrgubrgguwrb\n" +
            "wrgrurgbbrwbugwgwwrbugbrrggggrrwrrrrrbruurbggggbg\n" +
            "gwbwuurbgrubrbrugbubbubbwuurbbrwbrwrwubggwubgbburwbbbrwwbg\n" +
            "wbuwgwgurgubbbuurwgrgwgubwgwwugugwrbuwuuwgbg\n" +
            "ggwgrbubuwggbgwbwbrwuugwgrgbrgbggwrububwgwuwuwbgubbgbg\n" +
            "gguwrbbgbgurbggwwgbugguurubruwrgwrguurgbg\n" +
            "rbbggbrbuggrgruwgwwrguguuwgbuwrwrbuwgwbwwuw\n" +
            "uuwbgrwwubwwwguburgbrwwubggwrgwbrrruwguubu\n" +
            "uubguwwurwrwwrgwrbwgurgubrwgwwrurrgwbbuuwrbubbbwu\n" +
            "buwbwuwbbwbbbbwugbuwwuuwrrgwbwugbwwuguwrwggrubwwuwggrg\n" +
            "wbwwrwwwururbbrugbgrbbwuuuuurwrgwrrbgrgubuugrrwwrgbwruub\n" +
            "gwrwwgugbggwbrgbwbrbgggurrrwbbuuwrbwrwgrguuwbrruguwrgbg\n" +
            "gggwurgwwuubgruggugbubbguwbgrguwbwwrubggguruwrrbugrgbg\n" +
            "ubwggggguguuwuruwwruuugguwrggrrurbrgrbgbg\n" +
            "rwuuuwgbggruurrwwgwbrrggwbwbrugrugrbrbggbbwbrgwubggbwb\n" +
            "uwugwuurwbrguuwbbgbrbwuwgwrruuububwwrrgrubwwbrgwrggbgbubbr\n" +
            "wggrbuuuuwuuwgbrbbubbuugrbbgbbwbrbuwguruwbrwrwgrgrrurgbg\n" +
            "rggrrwgguguwwgbgwbbrgbubuwgrurguugguurgwwwwgrgbg\n" +
            "wubgbbbuwrubuuruggbwwrrwrggrbrgburbrbuwgbuwwgbg\n" +
            "ugwrubgwwgwbuwgwurwuwrrwbgbrrbwrwrbggbbgwgwbrrggbg\n" +
            "grgwruuwwrugurrbbuwbwubrbrwbrbbrbguugrrrgbwgrrggugw\n" +
            "ggrgggbwrgbuuurugurbwurwrrrgwuburrbggwwbubwgbg\n" +
            "wgggruugrggurwgubruwbbuwbwruuwgbrugrbggrgbrbrugugbg\n" +
            "wrrrwgggrrrbrwrbrgwrgwrurgrgggwbgwrbbbrgugwwgwguu\n" +
            "rbgggwruwugugwrugburuwgrubbrrgubgwbbrgwbgggbbwgguwgbrw\n" +
            "buwwbugwuuwgubuuwbbgugrwbwggrgbruguugwgwwwwrruwbg\n" +
            "uwwrwrbgbrrrwgbgugwurgwrbrwgurburrbuwgruuwurbbugbwwrrrbrgbg\n" +
            "bgururwbgwubwwbrrurgugurbuubwggrrrguubugwbwgbg\n" +
            "uwuwbbwrgwubrbuwwrwbubwggwwrgwubgrbwuwbguwg\n" +
            "grruurwrrubrubbruurgrgrbwbgbwgurbbruwgbbruubrgrwu\n" +
            "wuwrrrwubggubbwgbwbbbrbwbgwrrgbrrgubrguuruwgrbgw\n" +
            "rwbrugugubwbbwbwgrgwuubrbbwuwwuggrwwgugugubr\n" +
            "wugubwbgwwuguwrgrggwwgbrwgubgurwbrubgwrruwgruwwgbgbg\n" +
            "wugugubuurwbrgrbrwuuubruuuurgurbuwbwuuwbrrww\n" +
            "uwwrwrrwuugggwbrwrwggrbubbuuwbwwwwbruwuwwrgbgbg\n" +
            "burrwugbwrgbuwrugrbbbgubwuggbgrwbwubrugrbu\n" +
            "gbuubrubrwwwgrugrgugrguuwwrwwruurbwgwbuuurbbuuwubrb\n" +
            "bbbgrbbbubrwuurgggrbwruruubrurbwwwruuuuwggrgbru\n" +
            "ruwwwbwggwbwugugrurgwbubwrubgggrubwrururrwuwuuu\n" +
            "wrgwuwgwrwwuwgbgbuuruwurrrgggwwubwbgbrgbg\n" +
            "uwrrrggrbwbuubbbrrgbrguwbwwuguwrubwgwgwrbwurwuugwgbb\n" +
            "ugwrrggbgbruggbggugbbbuwruubrugbgrrwbwrwbwrrbgu\n" +
            "rurwugugrurwgwgrwgbuburguguuwuurbgbugguwugurrurgbg\n" +
            "wggbwrgrgwuwggbuurbbgugurbwubrugrbburgugrbrggwb\n" +
            "gbugbbgbuwbrrubwgrwwbwgrrbbuurbgrguwguuubwb\n" +
            "wrbbrwwuguurrwbrbwgurbuwrugubgwbgbgbubbggbwr\n" +
            "rgwrggbwubgubruurbugugugurrbrwggrgwbgbwrgrgru\n" +
            "rbububggrrbbbubbuwgrwuurbburubbbwguuwubwwburrrwu\n" +
            "uurrruubwggggrrbruuuwgbgrbbbwrbrguwgbwgwwrwbr\n" +
            "bubwgrguwrurrwwurrgwrbwbwggrgwggwruwgrrguwbggbbbguurwbrbru\n" +
            "ggrugubwuwrwggwbubguugrwgubggbbwgugbwwgbguwbuururrwurgg\n" +
            "ubrrrbuubugururuugggruwbbwurggwwwruggbwwwuu\n" +
            "ruurrbwrrurwrubbwwgrrgbgururgwbrruwgrwwwugwbuwgug\n" +
            "wrrggurwubrgrrwburggrbbuwgrrgbuwbggrguwuwgwrwrrgwrurbbgbg\n" +
            "wrwbwbuurgugrugbwwbguuwwgwbuggrwuurwwugbg\n" +
            "rbrbrbwggbbwwbbbbbuggwbbubuguwwuugrgbrruugggbbwbwwrwgbg\n" +
            "rwrwuwrwgurgugbbrrwwwugrbbwbrgbugbbgbrurrgbg\n" +
            "buuubwrgwwbrrwbwuwrubruggbwrbruwggrgrgwggrwggugwbbgguw\n" +
            "urggwbugguugubguwruwrbbgbgbrggurrubuwrgbg\n" +
            "wgbwggwbrwgbgruuguururrbbrgrwgwbwubgrrwguwgwuwuububgbg\n" +
            "gwwwbgurgbwrgwbuugurwbuurrrwrgrggggbwubwwgbg\n" +
            "bgbuwbgwubgbwgwrruubrrwwrrruwuggrgbrrubbbwugwbwrbgwgrbuu\n" +
            "ururubwbugbuwrgrwgburrwuurgwugrgbbgguwgguruwwbuuwgrwbrrbb\n" +
            "rgurgruuwwwuubbbbwrrrwwrrrrgrburrguruwgggwwwugbg\n" +
            "bgrbwwuuggrbwgwbwbwubuwrbuurwugbbbubrruubrgbg\n" +
            "uubugurrgbrguuruwurrwgbuuuwwuwbrrubgbgwugwgwbgbwubwwgr\n" +
            "gbgwugwwrgwgwuwwurrggbrugrwrgugugbbbwggbg\n" +
            "rbwuggbwguruggbggugrubwrubwwgrggbgguburuubbrrururwubrgggbg\n" +
            "bgrwuurubggwrrguguwubbguwgrwgbgrurwugrwgww\n" +
            "rrwuububrbbwgbwrrugbwbwuwugruwugbuwrbwgwrgw\n" +
            "bbggbguwbbbuwugbguuuwgbrguwwgwwbbruburgbbbbrurrwburuwggbg\n" +
            "bgurwgrurbwwurwrgggwrgbubugwuwbbbrgruuugrrrruggbrggbg\n" +
            "wrgwubrwwrrbubwuruurbbgbuwgwgurwgwggubrwrwbruuuwrug\n" +
            "ggrbuggbbbwrubwgwubrbrbburbgbgwrbwgwgrgggrbrwrgugruubrbb\n" +
            "rbrbbruwuugrrbgrububrgrggrurbrbrwbgwbrbwuguwgrwwwub\n" +
            "wgrrbgugwurrubbwrwgbuggrrurbgrrbwwuuwurwggbbwwruugru\n" +
            "brwuuwwbrrrbggbuwgbbgwrugurwuwbwgubbrgrgwgbbbgrugbg\n" +
            "uguwuburgbrggrrbubgurwgrbgrwuwuubrbrwrwruwwwbwgwrbg\n" +
            "rbbubuwbubbbbrwubbwrbugwrwubbwrbbgugbgwrbwuwuwgwrw\n" +
            "uuuubwbrubwwbrbuwbrgugwubrrurbgugugrbrbbrwggrwggrur\n" +
            "gguuugwwbwrbrgwurwwurruwbgwurgrgrbrgbwubggrwgbg\n" +
            "gggwrugrbwwugwgwuugugwbugbwwggugguwguugwwuwrbrgbbrbbrwurgbg\n" +
            "ubbuugbgbubwbuwwgrbgrrgbbwbbwrrgbugugwugwgggbg\n" +
            "guburbrrbrwubbgguguurrwuubrbrwrgbrbguwwbrrrb\n" +
            "bwubgbwwrwbwbgbubggwwwbgbgurruugwuruwugbugwugurbugrgbwwbgbg\n" +
            "uubrgrwwrrgrrbubrrbwggggrwruwuurrbbrwrgbwrugwbwgbg\n" +
            "uubbggbrwugwgbbgbrbrgbrggruwrubbwwwuurgububuwbrrurubbugbg\n" +
            "wwgwgwgwggrwruuwugbbrbwwgbgwugbgwwbgbuwbubuuguwwgruwu\n" +
            "wrrbruruugbugrwurbwrrwuwuguurgrbugrrgbwurrggugbg\n" +
            "gurrrwruwwruuwrgrbgwbbrurgwwwwwrgrrwrubwgggbgwbburrbguww\n" +
            "wwrwrubgrrwurbgbbbubrgrwbwrbrgbuwrubuuggbg\n" +
            "grbwgwgrbrbrwwbruwgrubgubuwrrrrgbbrugbubrwguuubbbrwgbg\n" +
            "brwuwwwrgggrgubruguurbwbrrrwbwrgggbbggwrgugbbbgurbggrwurwg\n" +
            "wrbbrwrggbbguugwugwgrrguwugubbbwgwwuggggbubuwwbwgguwwrrwbu\n" +
            "gbgwbrwrbgwbwbwwgwgbuwbuwbgbrbrbgbbbrggbg\n" +
            "bububbwrwgubgwwggbruggbbrwgbbubwbwwbwbgbwwwwwwwbrurwrr\n" +
            "rrgbgrbbubrbwwbgrrggbgrgwubgbugurwbgurgwwbuguwwgbg\n" +
            "bbbggburbwwwwugwuubrwbgwbwbgruwbrwubrrrggrrwrwwwrrgwbgbg\n" +
            "wwwurgbbuwgbgrurgbbgwguuuuuwwwrubugrwuwwwbrwwbggrggbg\n" +
            "urrrubwburgrbwgburgbbgrgrwrggrrbgubwugbg\n" +
            "rguwrwgguwuggwrrwurwbubbuwrbwrrrgwrugrrubburrrbbrbgbwgbwgbg\n" +
            "buwurrbgwuruwbuuggbwbggbruggurguuugrrbgbg\n" +
            "guwuubgrbwrwwbuuwuugbbbrwbuubuurugrwubrguuurwuuwrrbuwrgbg\n" +
            "bbubgggwuugwrugbubbguwwrgubwrrgburgwgurugbbbgubwrgbg\n" +
            "ruruwgurggguwrugubgrwrrrwggwugugbwgbgwrgbbuuuwrw\n" +
            "rgruuwugwugugbgwwwguruuguuwurururbrbbuwrwurgwubgbg\n" +
            "ggwgguuugwwwrbuuuurbbbwwwruwubgbgrgurbwugwubuwwwggg\n" +
            "gburgwuwrbbrwgwwgbgbwurrwbgbwbwrgbgwrrbrgwwgrrwrgggruugrgbg\n" +
            "wbbguuwuurrugbwuwuubwbbuuwgbrgbwwbgwururwb\n" +
            "gbwwwgbbggwwgbwurrgrbwrrbubwwgwbgwwrwwbwggwbrwgbg\n" +
            "wwgbwwuubwuwrbugwrrugbguwbbwgrwbrwbggwgbgrgb\n" +
            "rbbgguubbwwbubgbwgugugwuburwrwgwwuwurrbrbuwurrgggbgrbbwrg\n" +
            "urwgrwrbrgggrbuugbbruwubbgrwrgurbwwrbgwbrwrgbbgubbbr\n" +
            "bubuwwwwrubburgwgwwubwuwbubruwubrwwgggrgbubwuwubwuwuurgrub\n" +
            "wbbgrurrwbuwrgbbbrrguwwurwrwrrrwwwrbubwguguubbruwbrurrgwrgbg\n" +
            "uwubwwggrurbrwguubrrwgrwugrugwbubwbbrbuubggbg\n" +
            "bgwuwruugwwwwbbwbrugurwguwugwrbuguburbbgrgbrburwwrugu\n" +
            "urugrwwgwggguwgbrbwrrwrggrwuuguruwurgbuubrggbwgbgrruuu\n" +
            "wurggrrurubwbuwwgbgwbrbuwrwuurrbrrbrrwwwrgbg\n" +
            "wwbubrgbbugruguuuruggrwrwgburwwwrbwbrubruwwubgwwbwgr\n" +
            "wrrrrggrubuuuuuurggbwwgwbgwubbgwwbrrbbbgrbgbwubwbugbg\n" +
            "wbgrrgrbwwbugbbbbgbgrugbrbugwuwubuuwgwuubwgbgwuwgbrrww\n" +
            "bwgrrbggbgwrwugwruurwbwugwugwrurrwbrrguwrwwb\n" +
            "gbgurggugggubwwgwgbubggrgguubwbururgwbgbubbbwr\n" +
            "gbuubwgugubwwgwguuggwbgwbrwgbrrggbwwbgbg\n" +
            "wwwgrbrwuuuwgwwgugbbrgbgbbwgbgbrwguwwgrrububgwwgbbbbbb\n" +
            "uruwggrbrrwuruburrbwrwwwgwuwwwwuurwgwugrbwwuubuwg\n" +
            "rgwugrbruurgrrwbguruwwgubbrwrwbgubgbuuubuugbggwrg\n" +
            "brgwgruubuuuuggwuwuggrwgrbgbbwwuwwrgurgwwwu\n" +
            "bgrrgurrgwbbrrrwuugugubwgugrruuwwuwrwbwbgb\n" +
            "gburggbrugbbbubwwwruwurgwubbbubrburgbuurgbggbgb\n" +
            "bbgwbbbwrbuwurgbuuurbwgbbgguubuwgbguggbwbwrguwgrug\n" +
            "wuguwwwubwrrbbwuuwbgbwguwbgbuwubgbubbgrbwubwrburgwg\n" +
            "wrwrgwurbgwwurubrbwgrgugwwbrrwbwwwugrrrwwbrbruggur\n" +
            "uwgurrubgburrguuuubuuuuggwrwgwrbbruggrrwggbgubg\n" +
            "wgrwggrwrwwwwbbgbuuurrrbggbgugurrrrgrurggg\n" +
            "ubwgwbgburrbguuguwruubrbggrbggbbwuwubrgggb\n" +
            "rwguwrurburbwwubuggbbbubrugrbbbbgwggwrrrwrrgubgwwgww\n" +
            "ggguurrrgburgrbgggbwuubgrruguwwugrggrwrbgugrbbbrgrgu\n" +
            "bbrrburrbbbrrruurgburgbwrbuwuubbugwwuubwbrugw\n" +
            "brbwwwuugbggwurgbwrwrrwurrurwwgggurwwuububbwbwugbuubrr\n" +
            "grwwuuwuwbgrrwgbrwrwbbgggrguurgwgbuubwbgrgruwbubwurbgwggbg\n" +
            "gbubgbwbururrbwrrbuurwrburrgrgrgwwrrurrrrbgbg\n" +
            "guurbguugrgbbugwbbwbbuwwbruuuuruwgburuuruwggbgrwrbrwg\n" +
            "wwgrbbuwbuwuubrrbwwrbrgugububrwggrugbwrrurugbugrwgbrgubbub\n" +
            "ubwwrgugrurbbbbwurwrubuwrwgwwurbuubuwbgwuwubwubgwuuuwuwwbgbg\n" +
            "wgwgbgrwgrgrubuurrwrgrwwwbgbubbwwbrgbgwwrrwurbwrgwwgbg\n" +
            "rrubwubbgggrwrguguguwggwguwrwrgwwggrgubrwbrbwwugwr\n" +
            "gbrrrwuggbgwugurubrgbwrgrbwubbgbuwbggbgrwbrrbbrwggbug\n" +
            "grbrbrbbwgruurbbrgbrwgurbubuuwruurbwurbgbwwwbuwugrg\n" +
            "brbbrubbuguubwgugwururwgbwubguurgwbrbbggwurrgrwubb\n" +
            "wbgwgbwgbbggrwwbubwurbuwgwwbuwbrrwwgrwrrgbuuuguwwbubwugbg\n" +
            "urbgbbuubgburwgrubguggbbwwggburgrbuuurgrbuuub\n" +
            "grbggbwwuggwrbbgrwuwbrguwwwbwrbbbgrwrguubrgrbrwggbbrurgbg\n" +
            "rrbwwgbwwrrbrgwbwururrwgrwggbwrbruubrrgurwurggrgubgggubw\n" +
            "bgbrrrgwrbuurruuuububwgwuuguggrrbbwbggurrgbgbrgrrwggbbgb\n" +
            "ugbbbwuwbrwgbwbggubwwuuwwrgrgwrburgbwbbwbuubbrwgrrgwr\n" +
            "buubrbbbrwgwuurwggggubgrggbrwrbgbbbbbwrruuuggbg\n" +
            "ubuggbwgbrwrgguguggwurrwrrwubwguurwbwgwbrwrubggubbw\n" +
            "bububuurbgrwrrwrbrurruguwubrbrggrwrrwgwurwbguu\n" +
            "rubbwrwrwrrgrubwwgbruguburbrbwwrguggrbbwubugrrgwuwgrggbg\n" +
            "uwrrruugwgwbwugbrwrbrrburubggbrubbgbguwruwbwrwubgwggwbbugbg\n" +
            "gwugrguuwwbbgubbrgguruwwwbguuuuwgurwuwugubbgbg\n" +
            "wurrwubuubuwuwbuurrgugwuggbgwrrwbgbwbwguugggrwwgugb\n" +
            "wgwgbwwuggruguruuubgbwurrwbbbwwbrugwbgggbg\n" +
            "wrwubrubruuubrrgwugbbrguwugrbgwruwburbwuwbrgrubbrwubrrbub\n" +
            "wrwuwubruggugrruwbrgbbbgbgbuuurwbwrwgwbuwuugwbbuwwwrbggw\n" +
            "rruwbuuwbrbwrgrggwbuurrugruububbwgwbgwggubgubbgwgubgbg\n" +
            "buwwgrgwurgbgrbgbgbbrrggbggguwuwgurbwubbbrwbwwuwbu\n" +
            "wwbrggrgurwruubbuwwurgbrbbrbuugwbrbwburbgugb\n" +
            "bgbgwugwrbburbrwwwgwuwgurwruguwgruuguwgruwbgbwugwb\n" +
            "uwwgwuwgggwbrwggbrbbguwrgrbrggugwrbgbugugwrwurrbubb\n" +
            "rgbrgrrrwrgrwuwbrrurugurbgbwwwgbuwbrbuugwgrrbwbrgbugbg\n" +
            "gwrwgbgrrgbbbbggrrwugbwrwggurbrwrwwbwggubgr\n" +
            "bwbwrbrubwrwuwrrbuwbrguwrgbbuggbubrbugugbrbbwrgrurrgbg\n" +
            "uuwbwrgubbguubbbguuwugurrurwwgubrbgwgbwrrrrwwbwuuuuruwgbg\n" +
            "rbwrgbgbrbuugrwguguuwwuwubbrgggbgwrwrrwgwubww\n" +
            "bwwrbwrbbwruubuwrgrbgbwwwuwgurrurrwrguburubuwgbg\n" +
            "bgbrrbbrwbuwwgubrwubrugurwguwgugwbwwrubwbbubrgbwrrbwbuwrrgbg\n" +
            "bggbruggbwgrwugurbwwubuuuwgbgwruburgbrrwbwugbg\n" +
            "rwguwwrguwrggggwrgwrgwwwbwgrggwrubuuubwuuggwwugrbwburrw\n" +
            "uwrgbgbbgbbwurugrwwgburgubrwuuwbbwwwbrrrggugrruwugugbwg\n" +
            "uuwwbgruuguwgbbrrbubwubbgubbgggbgrwuuwrrgggru\n" +
            "ggbugwurwguwwgrbbgwrurgrbbgrwrguwwrwwurguwgrbrwguugwbrrgrg\n" +
            "bwrwugburgbbbrbwuugggrrgwrubrrrgbwrrbrwurrrwbb\n" +
            "wbwbgrrrrrbbwbbrguguwgururgurrwgwgguwburggggburgwguu\n" +
            "uuurgrbgwwrwwwbrurgbggubrrgwwwgbwgbuuwbbbwwurrbwbgbg\n" +
            "brubbguwgrugbrbugwrwwbguuugwrwrrwbrrgwbwwwbgwwubwbuwwurrb\n" +
            "wbrwbbrurgwguubwrwrwbbuwwgubruwrrgbrugrwwrbubwgbbu\n" +
            "guwgggburrwwbwgwggbrgbwrrrrubbggbuurguwrbbgrbwwbg\n" +
            "bwuwguuwwugrbgwgwubbguurubbbbbwrwggbggwurrugbb\n" +
            "brwgurwbwrrgbguwbubrwgrbrgwwbbuwwrburgbg\n" +
            "ubuuwgwgruugrurgububrgwubbuuwbwruwbgbgrwurbugbg\n" +
            "wuubwwugrwwbgbbubbguwgruwrbgwguurgbrubgguwu\n" +
            "gbwrwggrrrwwgurwurwwruwbuburrgurrwwurrbbgbg\n" +
            "rbwbrruwwwwwgbgbburrrrbwurwbugbrgwwgwrwwurbuggr\n" +
            "ugwggugubuuuwuwgubggrwgrugwrwubgwgbbugrwgbg\n" +
            "rwbggrbruubbbwgrwuwbrwrwbgwrbbwrbrwgggugubgbwugwgugugbruub\n" +
            "gwrbgrrbbburwgwwbrurbwbwwuguwrwrbgurburwbbrbgugwrbu\n";

    public static Input getData() {
        return new Input(trueData);
    }
}
